### ISSUE TITLE
Running Docker Redash image raises Python exceptions

### ISSUE THREAD

**Issue by AvivC** [getredash/redash#1039]
Hello, new to Redash (and Docker) here :)

I'm trying to install and run Redash. I have Docker running on my machine. All I did so far is:

    docker pull redash/redash
    docker run redash/redash

The terminal shows an exception is being raised from Python code:

    File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 442, in connect
        raise ConnectionError(self._error_message(e))
    ConnectionError: Error 111 connecting to localhost:6379. Connection refused.

Do I need to do anything more than `docker pull` and `docker run` in order to setup Redash on my machine?

If the answer is no, than what is the problem?

Thank you

**Comment by arikfr** [comment]
Redash requires Redis and PostgreSQL to run. You might want to use Docker Compose (http://docs.redash.io/en/latest/setup.html#docker-compose) to run it all.

In the future, please follow the instructions in the new issue template and use issues for bugs rather than support questions. Support questions belong in the discussion group: https://discuss.redash.io/c/support.
