### ISSUE TITLE
Unable to save the query

### ISSUE THREAD

**Issue by JAINMANISH512** [getredash/redash#1209]
Issue:
Recently, We tried to update redash to the latest version but we cancelled it and did a  rollback
But now we are not able to save any query.

Technical details:
Current Redash Version: re:dash 0.9.0
Browser/OS: Google Chrome Version 51.0.2704.106 (64-bit) / Mac OS X El Capitan Version 10.11.5 

[issue.pdf](https://github.com/getredash/redash/files/383120/issue.pdf)

**Comment by arikfr** [comment]
Check the logs (`/opt/redash/logs/api_error.log`) to see what is the actual error that happens when you save.

Also, do you have the output of the Fabric script run? It's not really possible to rollback an upgrade from some point.

(in the future please use the [Support Forum](https://discuss.redash.io/c/support) for questions like this one)

**Comment by arikfr** [comment]
Closing due to lack of feedback.

**Comment by JAINMANISH512** [comment]
Migration couldn't be reverted completely ,hence this issue occcured. Thanks for helping
