### ISSUE TITLE
Assistance with setting up Docker for Re:dash Instance

### ISSUE THREAD

**Issue by ashishbahuguna** [getredash/redash#1237]
Welcome to Redash's GitHub repo! 👋🎉

Hi Team,

I am pretty new with the Re:dash and we are planning to do a POC for Re:dash with Redshift and On Premises Oracle Database.
I am able to use the AWS image to connect to Redshift. However, I need assistance in setting up Docker for connecting to Oracle database, We have created a Virtual linux machine and now I want to use it for creating Re:dash instance as suggested in http://docs.redash.io/en/latest/setup.html#docker-compose.

Question: 

1. Would running the provisioning script listed in the link be sufficient to create Docker required for Re:dash as prerequisite or Do we need to do anything different to setup?
2. I see multiple changes to Docker files been done in the repository, how to know which one to be copied to setup Docker for creating Instance?
3. Is there any pre-baked image for Docker assistance I can download.

Appreciate your help and assistance.

**Comment by arikfr** [comment]
To have support for Oracle you need to install their libraries (they can't be preinstalled as you need to accept their TOS). If you use the Docker image, you will need to create a new Docker image that has these libs (you can base it on the official image `redash/redash`).

But currently Docker is _not_ the recommended way to run Redash, due to issues with upgrades/running migrations. We only recommend this for users who are comfortable with doing those steps manually. We plan to transition to Docker fully and make it the recommended way sometime towards October this year.

Is there any specific reason you would want to use Docker vs. plan install?

One last thing, please don't use GitHub issues for support questions like this one. We have a [support forum](https://discuss.redash.io) for this kind of discussions (it's mentioned in the issue template).
