### ISSUE TITLE
[Feature Request] Add missing values for date ranges

### ISSUE THREAD

**Issue by mhausdorf** [getredash/redash#1274]
If a chart is using Date values, missing Dates should be insert with null/0 values if this new option is selected.

**Comment by arikfr** [comment]
It's a bit tricky, because how do we know if the user wants to fill gaps every day? every hour? maybe every week?

But with most data sources, you can do this already by changing the query. Here's an example for Postgres: http://demo.redash.io/queries/2527/source.

One last thing, we try to keep the issue tracker for actionable issues only. This is why we ask to use [the forum](discuss.redash.io) for feature requests like this one. I'm closing this issue, but you're welcome to start a thread and we will continue the discussion over there.

Thanks.
