### ISSUE TITLE
Button to refresh all the queries in a dashboard

### ISSUE THREAD

**Issue by MarcoMene** [getredash/redash#1350]
It would be nice to have a refresh button in the dashboards to refresh all the queries included in the dashboard.

**Comment by arikfr** [comment]
Definitely. I think we need this button & a refresh interval setting like Kibana has.

**Comment by adamlwgriffiths** [comment]
We managed to add this to our branch. I'll see if it's able to be pushed back upstream.

**Comment by luke14free** [comment]
@adamlwgriffiths did you manage to do it? or shall I start implementing this?

**Comment by arikfr** [comment]
How about a refresh button along with a drop down next to it that allow
enabling periodic refresh? Then we can drop the current confusing auto
refresh implementation.

**Comment by adamlwgriffiths** [comment]
We've implemented it as a hack and are looking at doing a proper version to fix it up.
Something we're concerned about is the incoming Angular 1.5 re-write. The concern is it will invalidate the work we're doing at the moment.

As an aside, we're also looking to improve widget refresh itself, specifically changing widget updates to simply update the graph rather than delete, show spinner (which resizes the widget area causing the UI to move about), create new widget. It is a related change, but not part of this work.

If you think you can put an auto-refresh in quickly, by all means. Just let me know, otherwise it's pretty much the task we're working on during business hours.

**Comment by luke14free** [comment]
@adamlwgriffiths :+1: on it, have no idea how long it will take tho, but I will already work on the webpack branch so that it's already on angular 1.5

**Comment by arikfr** [comment]
> Something we're concerned about is the incoming Angular 1.5 re-write. The concern is it will invalidate the work we're doing at the moment.

That's why I've been slaving over this rewrite for the past weeks to get it over as soon as possible. :-) And indeed I encourage doing anything new on top of the `webpack` branch (as @luke14free did).

> As an aside, we're also looking to improve widget refresh itself, specifically changing widget updates to simply update the graph rather than delete, show spinner (which resizes the widget area causing the UI to move about), create new widget. It is a related change, but not part of this work.

Yeah, the size change is annoying. All the visualizations are written to "react" to changes in data, so it might not be that complex. Just need to change the way we handle the refresh & the UI we use to indicate refresh is in progress.

**Comment by luke14free** [comment]
I just added PR https://github.com/getredash/redash/pull/1410 to address this

**Comment by arikfr** [comment]
#1410 was merged 🎉  It will be part of the 1.0 release.
