### ISSUE TITLE
Unable to purge database connection cache

### ISSUE THREAD

**Issue by hhschu** [getredash/redash#1465]
New tables in the database does not show up in the connections page, nor can they be queried by SQL, days after they had been created in the database. The tables appeared only after we deleted the connection and re-created a new one to the same database. But after deleting/creating the connection, we have to modify all existing queries and chart. A _purge database connection cache_ button is good to have.

**Comment by arikfr** [comment]
Redash does not have persistent connections to the database. It opens a connection when you run a query and closes it when it's done. The schema is cached, but only for ~30 minutes, and it doesn't impact querying -- you can query tables that are not in the schema that shows in Redash.

If the tables didn't appear after a few days, it's clearly not because of Redash's cache. And if you couldn't query a table it means it was a restrictions imposed by your database. It's hard to tell why removing and adding the datasource solved this - maybe you used a different user.

The only thing to add in Redash is a button to refresh the schema, you can follow #1466 for this. But except that there is nothing else actionable here, so I'm closing this issue. You're welcome to continue the discussion and add more information that might shed more light on what happened.

**Comment by hhschu** [comment]
We don't know why deleting/creating works either. But I'm sure that _all_ connection information are the same, user included, before and after deleting/creating.

Before deleting the connection, we got an error of not enough permission to read, while connecting to the same database and querying the same table with the exact info as in redash through other SQL clients and CLI works smoothly. Very strange. (The environment is PostgreSQL 9.5 FYI)

We did aware, from the document, that the schema is refreshed every 30 minutes. That got us wonder why after several days the schema has still not been updated, hence this issue and suspicion of a connection cache has been maintained.

Thanks for clearing on the issue and we do hope these further information would help resolve this weird behavior.

**Comment by arikfr** [comment]
This error comes directly from Postgres. Redash does not enforce its own restrictions, as you can see [here](https://github.com/getredash/redash/blob/master/redash/query_runner/pg.py#L119-L155).

You can update your existing queries directly in the database to associate them with the new data source. You only need to update the queries to restore everything back to what it was.
