### ISSUE TITLE
Error running query: FATAL: remaining connection slots are reserved for non-replication superuser connections 

### ISSUE THREAD

**Issue by rockwotj** [getredash/redash#1561]
### Issue Summary

Getting a lot of 
```
Error running query: FATAL: remaining connection slots are reserved for non-replication superuser connections 
```

In the newest version of redash

### Technical details:

* Redash Version: 1.0.0-rc
* Browser/OS: Chrome
* How did you install Redash: From Source

**Comment by arikfr** [comment]
Looks like you maxed out the number of allowed connections to your PostgreSQL database.

If it's the metadata database of Redash:
1. Make sure you don't have old Redash processes running and keeping open connections.
2. What's your number of allowed open connections to the database?

**Comment by rockwotj** [comment]
It's the metadata database for Redash.

So we have 36 workers total, and the redash web frontend itself, totally they are using 94 connection atm (very little usage if any). Is there a reason so many connections are open? Are they not pooled? How many connection can be opened by a single worker?

Do you have recommended numbers for this?

**Comment by arikfr** [comment]
Can you shut down the workers and see how many connections get closed? I have a feeling the issue is with the workers, but want to make sure.

**Comment by rockwotj** [comment]
All but 5 or 6 got closed when I shut down the workers

**Comment by arikfr** [comment]
I have a feeling there are two things that happen here:

1. Each Celery worker "sub"-process (the actual process that does the work and gets killed after 10 tasks), uses its own connection pool. But on exit they don't close those connections to they keep lingering. 
2. SQLAlchemy creates too many connections instead of reusing existing ones (otherwise no reason for each worker to use more than one connection) until it reaches the maximum number of connections allowed for the pool.

Still debugging this though. Any input will be appreciated.

**Comment by rockwotj** [comment]
I bumped the max connections to 500 and everything has been okay since then. Right now we have  135 connections (I don't think anyone is using it at the moment though).

```
> SELECT state, COUNT(*) FROM pg_stat_activity GROUP BY state;
 state  | count 
--------+-------
 active |     1
 idle   |   138
```
