### ISSUE TITLE
Crashes on Heroku with

### ISSUE THREAD

**Issue by mtimofiiv** [getredash/redash#1573]
### Issue Summary

On Heroku, the launch of the web dyno fails. In the Procfile, the web dyno is told to:

```
web: ./manage.py runserver -d -r -p $PORT --host 0.0.0.0
```

For me, this made the following log entries to happen:

```
heroku/web.1:  Starting process with command `./manage.py runserver -d -r -p 13269 --host 0.0.0.0`
app/web.1:  Error: no such option: -d
heroku/web.1:  Process exited with status 2 
heroku/web.1:  State changed from starting to crashed 
```

### Steps to Reproduce

1. Create an app on heroku
2. Add 2 buildpacks, one for the python and one for nodejs:

```
heroku buildpacks:set heroku/python --app=appname
heroku buildpacks:add --index 1 heroku/nodejs --app=appname
```

3. Add in the Redis, Postgres, Google Auth env variables
4. Deploy Redash into that app

### Technical details:

* Redash Version: current `master`

**Comment by arikfr** [comment]
Oops. The Procfile.heroku file is a left over from old support for Heroku...

While it's possible to deploy Redash on Heroku (you just need to adjust the runserver command), I don't recommend it. Soon enough you find out that the free tier of Redis is not enough and at a later stage the free tier for PostgreSQL is not enough. At this point, you might as well spin a DigitalOcean droplet, that will cost less.

I guess that Heroku is appealing for those who have their whole stack there, but otherwise I wouldn't recommend it.

If you still want to make it work, change the command to:
`gunicorn -b 0.0.0.0:$PORT -w4 redash.wsgi:app`
(you might want to adjust the number of workers: `-w4`)

**Comment by Skeyelab** [comment]
Say someone had access to an unlimited Heroku account, 

Are you saying the web process should be:
```web: ./manage.py gunicorn -b 0.0.0.0:$PORT -w4 redash.wsgi:app```

**Comment by n4cr** [comment]
@Skeyelab no drop the `./manage.py`
