### ISSUE TITLE
Deleting datasource deletes all queries associated with it

### ISSUE THREAD

**Issue by subhajeet2107** [getredash/redash#1808]
I accidently deleted datasource from the admin panel, now all the queries which used to ran on this datasource also got deleted, is there any way i can retrieve them back ? we donot have backup of postgres db running with redash.

**Comment by arikfr** [comment]
They are not deleted, but because they have no data source associated with them, they don't show up in the lists (as no one has permission to view them).

You can associate them with a new data source by updating directly in your database the `queries` table (look for rows with `data_source_id` equal to `null`).

In the future, please use the [forum](discuss.redash.io) for support questions.
