### ISSUE TITLE
Missing Datasource Types on 2.0.0

### ISSUE THREAD

**Issue by Rovel** [getredash/redash#2001]
Hi, 

I've just updated my aws ec2 Redash 2.0.0+b2990 and as I was going to add a Google Spreadsheet as a Datasource I found that the name was missing from the sources list as the print shows:

And some others source types were missing too, any changes that I'm missing?

![screen shot 2017-10-06 at 11 31 54](https://user-images.githubusercontent.com/2469500/31282878-4166817c-aa8a-11e7-8bcf-60fe3702d4cd.png)

**Comment by arikfr** [comment]
Please refer to the Troubleshooting section in the upgrade guide: https://redash.io/help-onpremise/maintenance/how-to-upgrade-redash.html. The BigQuery part is relevant to the Google Spreadsheets too.

Also, please use the forum for such support questions. There is even a thread about this: https://discuss.redash.io/t/googleanalytics-and-spreadsheet-are-not-listed-in-datasource-type-since-v2-0-0/1026.

**Comment by Rovel** [comment]
Thanks!! :)


Filipe Veloso
Diretor de Tecnologia e Operações
Tel. 55 11 2386-2001
Cel. 55 11 99195-3155
www.umanni.com.br
Responda a nossa pesquisa de satisfação:
https://goo.gl/forms/kYP9pK0mShvDgW7F2


2017-10-09 7:17 GMT-03:00 Arik Fraimovich <notifications@github.com>:
