### ISSUE TITLE
Switch to yarn instead of npm

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#2212]
When it was released `yarn` had a lot of advantages over `npm`, but `npm` closed of the gap over time. Yet, I think that `yarn`'s [auto detect and merge lockfile conflicts](https://github.com/yarnpkg/yarn/pull/3544) feature tips the scale towards switching over.

- [ ] Run `yarn` and commit `yarn.lock` to the repo (while removing `package-lock.json`).
- [ ] Update `Dockerfile`.
- [ ] Update `circle.yml`.
- [ ] Update documentation.

**Comment by arikfr** [comment]
@kravets-levko wdyt?

**Comment by kravets-levko** [comment]
IMHO, at this time `yarn` and `npm` are more or less equal when comparing their features, so it's hard to choose one over another. I prefer to use `npm` just because it's installed by default - so no need to install additional packages (I mean - `npm i -g yarn :-) )

About lockfile conflicts - I haven't seen any for last few years (no lie), so, I think, we will not win anything from switching to `yarn` (especially if keep in mind that we're adding/upgrading dependencies very carefully).

So , that's my opinion, but the final decision is up to you.

**Comment by arikfr** [comment]
Using npm as it's installed by default was the main reason I never switched until now. 

But the lock file conflicts are real pain -- every time someone updates `package.json` and I run `npm i` I get a different `package-lock.json` file than the one checked in the repo.. I just never commit my version to avoid the headache :)

**Comment by kravets-levko** [comment]
@arikfr I think it depends on how often do we have `package-lock.json` conflicts. Because if we have it only sometimes, I don't think we need to switch from `npm` to `yarn`. But if it happens quite often - then it makes sense.

**Comment by ranbena** [comment]
I have these kinds of conflicts at least once a week with Redash.
Might be something I'm doing wrong but if yarn fixes that, I'm for yarn.

**Comment by arikfr** [comment]
Closed by #5541.
