### ISSUE TITLE
Not receiving alert emails SMTP

### ISSUE THREAD

**Issue by Felhamed** [getredash/redash#2224]
### Issue Summary

Using redash/redash:4.0.0.b3331 (docker image) I am able to send a test email however I am not receiving alert emails.

### Steps to Reproduce

Adding mail server options into docker-compose.yml
      REDASH_MAIL_SERVER: smtp.migadu.com
      REDASH_MAIL_PORT: 587
      REDASH_MAIL_USE_TLS: "true"
      REDASH_MAIL_USERNAME: "test@example.com"
      REDASH_MAIL_PASSWORD: "password"
      REDASH_MAIL_DEFAULT_SENDER: "test@example.com"
      REDASH_HOST: "http://example.com"

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

I can send a test email via bin/run ./manage.py send_test_mail test@gmail.com however, when I try to set an email alert I don't get the email.

**Comment by krostel** [comment]
I had the same issue (using the docker image too) and it was due to my environment variables related to mail being set up only for the redash server and not for the redash worker.
Try bin/run ./manage.py send_test_mail in the worker's shell and see if that works. If not you can check the logs on the worker for the errors and check if REDASH_MAIL_SERVER and the others are set up on it correctly, and then change deployment accordingly.

**Comment by Felhamed** [comment]
I tried your suggestion and I was able to send via manage.py in the worker shell, yet I still wasn't able to get alert emails. However, upgrading to v4.0.0.b3387 fixed it for me so I will close this issue. Thanks for your help.

**Comment by RichardLitt** [comment]
Thank you for keeping us updated, @Felhamed!
