### ISSUE TITLE
Auto height for some of the visualization types

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#2274]
Some of our visualization types can adjust to the container they are given, while others don't. The later one include: Table, Pivot Table and Cohort. The current behavior where each of those has a static size creates a bad experience for the user, who more often than not need to update the size of the widget after placing it.

I think that we should keep using auto size for these widgets, unless the user resizes them.

**Comment by arikfr** [comment]
@kocsmy @kravets-levko wdyt?

**Comment by kocsmy** [comment]
This is a tricky question. If we think about the widgets that are way too big compared to the content inside, then yes, we'll need to make the widgets smaller and make them adopt to it's content.

But there's also a maximum we should set in case we have a very wide / long table or visualisation, so it won't get too big. (Imagine a 40 columns table with thousands of rows)

So yes, I agree that auto-sizing would improve the experience but also set a maximum that it can grow, and the user can still adjust it bigger/smaller to their taste.

**Comment by arikfr** [comment]
> But there's also a maximum we should set in case we have a very wide / long table or visualisation, so it won't get too big. (Imagine a 40 columns table with thousands of rows)

This is not really an issue:

* Auto sizing is only for height. Width stays fixed.
* We still have pagination :-)

**Comment by kravets-levko** [comment]
> This is a tricky question

+1 :-)

IMHO, we should avoid using auto-height feature anywhere except of backward-compatibility (old dashboards). The main reason "why" - because this feature makes the dashboard unpredictable - you can place all widgets perfectly, and one day some of them will have more data, which will lead to auto-sizing, and will break the layout. And you should always remember, that auto-height will work only to first layout editing; after layout saved - auto-height will get disabled. It works fine for old dashboards, because it worked in similar way earlier (there were two columns and *all* widgets has auto-height).

With new dashboard, we should think about widgets in another way. When we add widget, it has a default size. It's like a recommendation, but if user see that widget is too small or too large - he should just resize it. It's predictable - user will always know that his dashboard will look exactly as he sees, even if data will later change. When we have auto-sizing enabled - user should keep in mind all possible combinations and cases, - it does not fit WISYWIG principle.

Yes, we still have auto-height by default for some rarely used widgets, it's because that widgets still have fixed size (cannot fit the container). But I think, in future we should update them too and stop using auto-sizing feature anywhere except old dashboards. Just because with that feature it's hard to predict how dashboard will look.

**Comment by arikfr** [comment]
I'm not sure that preserving the order the user placed the widgets is such a high priority. It's not an art project, it's just a dashboard :-)

But we can do the following: when you place a {table, cohort, pivot} visualization on a dashboard, we measure it and set the size. So the initial size is based on the _current_ content, but it's fixed after that (unless the user updates its size manually).

The only drawback with the above is that the row height increments might cause us to have widgets with empty space at the bottom.

**Comment by deecay** [comment]
FYI

for query page's pivot viz:
multi-filter looks like this (clipped),
![image](https://user-images.githubusercontent.com/1698635/37202379-b24d7442-23cd-11e8-875b-e3623ff1a7cc.png)

pivot control renderer/aggregator dropdown look like this,
![image](https://user-images.githubusercontent.com/1698635/37202561-24664e1e-23ce-11e8-858f-fa8970703b56.png)

and value filter (clipped),
![image](https://user-images.githubusercontent.com/1698635/37202586-3c71b8d6-23ce-11e8-97a2-4a7121d629eb.png)

**Comment by kocsmy** [comment]
thanks, @deecay — we'll align these interfaces to match the new style.  In fact, we just improved pivot table design a bit to fit in more as it looked very old.

**Comment by arikfr** [comment]
This was implemented as part of recent fixes to the dashboard layout engine.
