### ISSUE TITLE
"clear" multi filter should be the same as select all ..

### ISSUE THREAD

**Issue by darylerwin** [getredash/redash#2293]
### Issue Summary

A summary of the issue and the browser/OS environment in which it occurs.

### Steps to Reproduce

1. When you click clear all in the filter .. all the rows should be returned - ie no filter at all
2. as it is now, you have to select all which is fine, but confusing.

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Redash Version: 4.0

**Comment by darylerwin** [comment]
Appears to be covered in PR #2262

**Comment by tonyjiangh** [comment]
> Appears to be covered in PR #2262

Not yet I guess.
I guess what you mean is that clear should select all value, but currently it removes all.

I tend to leave both select all and clear as it is, because there're these two cases to cover:

- When you only want to select one value
   - clear -> select one value
- When you want to select all but one value
   - select all -> remove one value

WDYT?

(Although the above PR currently would disable the second case, I guess I'll have to tackle that)

**Comment by darylerwin** [comment]
Clear removes all filters .. so hence all the data should be displayed.

**Comment by tonyjiangh** [comment]
Ah, now I get what you mean. You're right. I'll fix that.

**Comment by nunesbeto** [comment]
+1
