### ISSUE TITLE
Can't connect to mysql

### ISSUE THREAD

**Issue by gclsoft** [getredash/redash#2333]
```
Connection Test Failed:
Can't connect to MySQL server on '127.0.0.1' (111)
```
`mysql -h 127.0.0.1 -P 3306 -uroot -p1 ` is ok on the ubuntu commend

**Comment by arikfr** [comment]
This looks like a setup issue and not something Redash specific. Unfortunately don't have enough information to help (like how did you setup Redash? Is Redash running on the same server?).

Please provide the extra details **in a [forum](https://discuss.redash.io/c/support) post**.

If you still believe this is a Redash specific issue, you're welcome to reopen with extra details.

Thanks.

**Comment by gclsoft** [comment]
@arikfr I set up from docker:
```
Run docker-compose -f docker-compose.production.yml run --rm server create_db to setup the database.
Run docker-compose -f docker-compose.production.yml up
Run docker-machine ls, take note of the ip for the Docker machine you are using, and open the web browser.
Visit that Docker machine IP at port 80, and you should see a Redash login screen.
```
The mysql is installed in the same server with redash

**Comment by arikfr** [comment]
It could be nice if you had the courtesy to follow the instructions when seeking for help, but ... :man_shrugging: 

Anyway, the issue is that Redash runs in a Docker container, which by default is on isolated network from your localhost. For it, localhost is the Docker container.

You can either use the host IP instead of localhost (and make sure MySQL is binded to this IP) or change the networking mode in your Docker compose settings.

Nothing Redash specific here.

**Comment by gclsoft** [comment]
@arikfr Thanks so much. You're right. 
It is OK now!
```
Use this command:

GRANT ALL ON yourdatabasename.* TO root@'%' IDENTIFIED BY 'yourRootPassword';
Then:

FLUSH PRIVILEGES; 
Then comment out the below line in file "/etc/mysql/mysql.conf.d/mysqld.cnf" (is required!):

bind-address = 127.0.0.1 
```
