### ISSUE TITLE
database schema NOT shown with psql read-only user privileges

### ISSUE THREAD

**Issue by changchichung** [getredash/redash#2432]
### Issue Summary

I wanna to connect a dbuser with readonly privileges in psql to redash by below command.

```
psql 
\c db_name
CREATE USER readonlyuserName WITH ENCRYPTED PASSWORD 'readonlyuserNamepassword';
GRANT CONNECT ON DATABASE db_name TO readonlyuserName;
GRANT USAGE ON SCHEMA public TO readonlyuserName;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO readonlyuserName;
GRANT SELECT ON ALL TABLES IN SCHEMA public to readonlyuserName;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO readonlyuserName;
```

it`s ok to connect to db and execute SQL commands , but the database schema not shown as a full privileges do .

#### Full Privileges Users screenshot
![https://i.imgur.com/dItrV5b.png](https://i.imgur.com/dItrV5b.png)

#### read only users screenshot
![https://i.imgur.com/xt0Y95O.png](https://i.imgur.com/xt0Y95O.png)

database schema missing!!

How to enable correct privileges to a psql "read only" user with database schema ? thanks !

* Redash Version: 3.0.0+b3134
* Browser/OS: Firefox / ubuntu 16.04
* How did you install Redash: provision script

**Comment by RichardLitt** [comment]
Thanks @changchichung. Have you tried opening this on the support forum?

**Comment by changchichung** [comment]
yes , but no response there :weary:

**Comment by RichardLitt** [comment]
Ok. We need to replicate this; if it is a bug, then it should be filed here and we'll deal with it. If not, then the forum really is the best place for this. Thanks.

**Comment by nitingrewal** [comment]
Any luck on this bug/issue?

**Comment by arikfr** [comment]
I doubt this is an actual bug, because I'm personally using Postgres read only user and can get the schema. So it's more likely a setup issue.

In your case I would:

1. Try making a a query, to see if it's actually a schema issue or something more basic in your grants.
2. If querying works, I would run a schema refresh and check the logs to see if there are any errors.

If you have further questions, please use the forum. It's a community resource, so people respond on their free will. But not getting a response there is not a reason to clutter the issues :-)

Good luck!
