### ISSUE TITLE
Tiring Design Refinement Color Scheme

### ISSUE THREAD

**Issue by AzureusCorp** [getredash/redash#2476]
Hey.

We've been running v4.0 for a week now at work and enjoy the new functionalities it brings. However, almost everybody (~20 users) complains about the new color scheme being too tiring.

1. Is it at all possible to tweak the color scheme a bit? The combination of full white + the new oversatured colors in charts make looking at charts/dashboards very tiring.

We've been running v4.0 for a week now at work and everybody (~20 users) complains about the new color scheme being too tiring.

Compare these screenshots with a dashboard from v4 with another one from v3. Bear in mind that the v3 one is a lot more colorful, but also less tiring.

I didn't get to make the v3 dashboard in v4 as well, for an exact comparison, but what I'm talking about should be clearly visible with these examples as well:

<img width="1661" alt="new_dasbhoard" src="https://user-images.githubusercontent.com/2837256/39042884-ab5b87ae-4494-11e8-9a0e-507f3acf8b6b.png">
<img width="1708" alt="old_dashboard" src="https://user-images.githubusercontent.com/2837256/39042727-3a64260a-4494-11e8-86d5-057ab2c35696.png">

2. When looking at queries, there is now a lot of wasted space for the "database tables" column: 

<img width="1440" alt="wasted_space" src="https://user-images.githubusercontent.com/2837256/39042200-ebbf0476-4492-11e8-95d1-b7947a08e29b.png">

Furthermore, once collapsed, it does not remember to stay collapsed so we have to collapse it for every query we open/view.

**Comment by arikfr** [comment]
Thank you for the feedback, @AzureusCorp. I will be appreciate if you could elaborate on what you mean by tiring? 

To make this more actionable, I opened several issues to document the solutions for your feedback:

* #2479 - remember query editor panes state.
* #2480 - option to pick a customer color in the color picker.
* #2481 - option to customize the color theme.

It's not on our immediate roadmap, so we will appreciate help from the community.

I'm closing this now, but you're welcome to continue the discussion.

**Comment by lsh-0** [comment]
hi, I'm brand new to Redash and the very first thing I did after getting an instance running locally was look for some sort of theme or colour control (and not finding any). 

1. the low contrast between the vast expanse of white and the light grey text is 'tiring'. For example:

![Screenshot at 2022-01-28 11-38-13](https://user-images.githubusercontent.com/2142748/151469219-41009b6f-aacc-4c83-85e2-b00ecd9848f1.png)

and

![Screenshot at 2022-01-28 11-42-20](https://user-images.githubusercontent.com/2142748/151469573-6adf9aa6-d608-4818-a04b-3f0f9061d9a4.png)

it may look pretty from a designer's POV, but looking at this for only a few seconds makes my eyes hurt.

2. the fonts are thin
3. the text is too small
4. the icons are obscure (but the tooltips are great)
5. little patches of colour, because of the large space of white and low-contrast fonts, icons, widgets, have 'glare' and they pull the eye around the screen, for example the two bright blue buttons in the screenshot above. Why do I want 'create' when I'm already on the 'create' screen? why do I want to 'Execute' when there is nothing to execute?

Slabbing in some colour and zooming the interface about 130% helps a bit:

![Screenshot at 2022-01-28 11-54-42](https://user-images.githubusercontent.com/2142748/151470782-c3cf1ab8-f318-41b5-b56a-fb8363824e4c.png)
