### ISSUE TITLE
Receive communication error when Athena returns NaN value

### ISSUE THREAD

**Issue by tdawber** [getredash/redash#2544]
### Issue Summary

When Athena returns a NaN or Infinity value, generally as a result of dividing by 0.0, the following error is displayed:

“Error running query: failed communicating with server. Please check your Internet connection and try again.”

This error message is confusing, and the result could also be handled more nicely.

### Steps to Reproduce

1. execute the following query on an Athena connection:

select 1.0/0.0

When you divide an integer value by an integer zero (select 1/0), Athena throws the error "Error running query: DIVISION_BY_ZERO: / by zero" and this is presented nicely in Redash.

It would be good if either Redash throw a meaningful error upon being unable to handle the Infinity/Nan value, or if it displayed all results and presented null or some other value in place of Infinity/Nan.

### Technical details:

* Redash Version: 4.0.1

**Comment by arikfr** [comment]
The issue is due to `json.dumps` sending the value as `Infinity`, which is considered an error by the JSON parser in the browser (see example below).

```json
{  
   "query_result":{  
      "data":{  
         "rows":[  
            {  
               "_col0":Infinity
            }
         ],
     }
   }
}
```

So there are two issues here:

1. We show the wrong message to the user: there wasn't a communication error, but we failed to parse the response.
2. We should send values the browser understands... Although I'm not sure what we should send in such case? `null`?
