### ISSUE TITLE
Date Range Type Parameter

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#2643]
We need support for adding a _Date Range_ typed parameter. The tricky part here is that date ranges have two values and not only one.

We should use [this](http://www.daterangepicker.com/) or similar as the UI. What I really like in this picker is the predefined date ranges.

**Comment by nadavivry** [comment]
I would suggest looking into "Ant Desing" design system which comes with a wide set of components, including date-picker components (I recently reviewed a few design systems in order to find a general solution to my own app and chose this one).

You can take a look at multiple examples, including date-range selection examples here:
https://ant.design/components/date-picker/

Note that they support predefined date ranges as well ("Presetted Ranges").

Besides date-range picker and date-picker in general, I think that Ant Design components set answer most of the use cases for Redash, whether for query parameters or other parts.

Now that we can implement React components in Redash, it can work smoothly.

**Comment by arikfr** [comment]
Thanks for the tip, @nadavivry.

Do you know if we were to use a single component from Ant, is there some extra baggage that comes from it being a full design system, or each component is standalone?

**Comment by nadavivry** [comment]
According to the "Manually import" example in the following page, looks like it won't be a problem to import each component independently and avoid the extra baggage:
https://ant.design/docs/react/introduce#Use-modularized-antd

In any case, using Webpack with "Tree shaking", you shouldn't be worried of an extra baggage at all (in this case or others).

**Comment by arikfr** [comment]
Cool! It's definitely one of the better options I've seen so far and at least some of the other components will be useful too.
