### ISSUE TITLE
Autocomplete sometimes stops working

### ISSUE THREAD

**Issue by emtwo** [getredash/redash#2707]
A summary of the issue and the browser/OS environment in which it occurs.

* Issue occurs in both Chrome and Firefox
* Reproduced on osx

### Steps to Reproduce

1. Using either Athena or Presto as a data source, type a character that should trigger an autocomplete (e.g. `a` should autocomplete to `avg`). The autocomplete dropdown appears

2. Delete the typed character and type it again.

Expected Behaviour: The dropdown shows up again.
Actual Behaviour: The dropdown no longer works after the first time a character is typed and deleted. It works again after refreshing the page but the same issue gets triggered.

Note: This worked fine on other data sources, for example, Redshift.
Note: This was reproduced in the mozilla fork of Redash

**Comment by arikfr** [comment]
I have a feeling it has to do with the amount of tokens the data source has. 

Does it show up if you try to trigger it manually (Ctrl + Space)?

**Comment by lomkju** [comment]
I can confirm this. Autocomplete works with (Ctrl + Space) on sources with huge amounts of tokens but doesn't work on its own. The data sources where amount of tokens is less the autocomplete works flawlessly. Any fixes for this ?

**Comment by arikfr** [comment]
> I can confirm this. Autocomplete works with (Ctrl + Space) on sources with huge amounts of tokens but doesn't work on its own.

This is the intended behavior (also documented in the knowledge base).

**Comment by lomkju** [comment]
Any particular reason this is disabled when having a lot of tokens performance impact?  How can we enable this even if the token size is greater than 5000?

**Comment by arikfr** [comment]
@lomkju yes, the reason is performance.

**Comment by arikfr** [comment]
@emtwo I found out that your fork's implementation is a bit different than the upstream one, and this is why autocomplete stops working completely and can't be even triggered with Ctlr+Space.

The issue is here:

https://github.com/mozilla/redash/blob/d1a32370cd4f4fe75c4f3d63d12092817f481235/client/app/components/queries/query-editor.js#L105-L111

Note that in the upstream we don't disable basic autocomplete, even when tokens count is higher than the threshold:

https://github.com/getredash/redash/blob/8c5e2dffc471db974f11df1102d8f783d9fb1554/client/app/components/queries/query-editor.js#L104-L107

**Comment by arikfr** [comment]
Btw, in current master the behavior is similar to your fork, as we don't enable basic autocomplete at all. But I'm going to fix this soon.

**Comment by emtwo** [comment]
@arikfr thanks so much for looking into that and for the update! That is super helpful!
