### ISSUE TITLE
Datetime format on CSV is different.

### ISSUE THREAD

**Issue by michaelsolla** [getredash/redash#2751]
Re-opening from issue #2557 since it otherwise is the same situation we are in:

---
Issue Summary
When I download CSV file on the queries page,
the datetime format that CSV has is not as same as an original data.
is this a bug or a feature?

Original data on MySQL is "2018-01-23 14:00:30"
Redash CSV is "2018-01-23T14:00:30"

I'd like to get rid of "T".

Redash Version: redash:4.0.0-rc.1
Browser/OS: Chrome
How did you install Redash: Docker

---

Now I did see the workaround for this:

`SELECT DATE_FORMAT(NOW(), '%Y-%m-%d %H:%i:%s') now;`

However as we use Redash across many queries with many people it would seem a bit silly to have everyone use the workaround since it otherwise is not an issue if used directly with the database.  Is there a global environment setting or something we can change to make ReDash not put the T in the date format?

Thanks!

**Comment by arikfr** [comment]
When we store the query result we serialize it into JSON, because JSON doesn't have a native DateTime type, we use a standard format for these values. Later when we serialize the data into CSV we use the same JSON content, which was already converted into this standard format.

One possible solution is to detect these types when we serialize into CSV, and use the setting we have for DateTime format to render them properly (similar to what we do in the UI).
