### ISSUE TITLE
Support for Presto username and password

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#2925]
Currently the Presto query runner supports username only. We should support password as well.

This probably requires upgrading the PyHive library.

**Comment by Ralnoc** [comment]
I have opened PR #3723 that resolves this issue as well as improved support for usernames when not configured through the data source. (For example if you are using SAML auth and want it to honor the original user) And changes the source from `pyhive` to `redash` to remove confusion.

* Username: It uses the configured field for username over all else, then uses the email address to extract the username based on the left side of the `@` symbol in the email address and finally, if all of that is missing, defaults to `redash`.
* Password: is pulled from a new password field in the configuration page for Presto
* Source Identifier: It changes the `source` identifier for `pyhive` so that instead of reporting itself as `pyhive` to Presto, it declares itself as `redash`.

**Comment by arikfr** [comment]
This is not related to the issue, but I assume that the issue author or followers might have SAML enabled for their deployment and should be aware of the following Security Advisory: https://github.com/getredash/redash/discussions/5961. This affects *all* Redash versions and should be patched immediately.
