### ISSUE TITLE
Backslash in dropdown list value transformed to &#x2F; in query

### ISSUE THREAD

**Issue by GilAdirim** [getredash/redash#3042]
I'm using parameters to filter a query. The values of the parameter are pre-calculated by a query. One of the values is `Other/Organic`.
When I select this value in the dropdown and execute the query, the underlying string in the SQL is changed to `Other&#x2F;Oranic`.

Redash Version: Hosted (master?)

**Comment by kravets-levko** [comment]
Hi! Can you try to use three curly braces for the parameter (i.e. `{{{ param }}}`) and tell me if it works? Thanks!

**Comment by GilAdirim** [comment]
Yes, that works - although I don't remember seeing anything about it in the documentation...

**Comment by kravets-levko** [comment]
Well, we also noticed this few days ago - another user asked similar question on the forum. Therefore there are no anything about this in the docs. 

We use [Mustache](https://mustache.github.io/) to substitute parameter values, but by default it html-escapes some characters like `<`, `>`, `&` or `/`. Three curly braces allow to use unescaped value.

I'll close this issue because your problem is solved; the proper fix will be available soon.

**Comment by kravets-levko** [comment]
@arikfr, hm, I missed that we use `pystache` on backend. Will fix it and then ping you
