### ISSUE TITLE
remove widget in dashboard works only once

### ISSUE THREAD

**Issue by araker** [getredash/redash#3202]
### Issue Summary

When removing multiple widgets in a dashboard, I can only perform the action once. The second time I click on the 'cross' of a widget the 'are you sure' dialog doesn't appear and the widget isn't removed. When I refresh the page, I can remove one widget again. 

### Steps to Reproduce

1. Create a dashboard
2. add two widgets 
3. remove the first widget
4. remove the second widget, this doesn't work

I expect that I can remove multiple widgets, without refreshing the page in between. 

### Technical details:
* Redash Version: 6.0.0+b8537
* Browser/OS: chromium 66.3359.139 Ubuntu
* How did you install Redash: Ami docker version

**Comment by arikfr** [comment]
@ranbena no point in addressing this now, but just make sure to address it when working on the React grid.

**Comment by kravets-levko** [comment]
@arikfr @ranbena This issue is related to `gridster` library which we use to dashboard layout - sometimes it hooks up a bit more events than needed, and our event handlers stop working. I tried to find fix for it, but after migrating to React this problem should just disappear (if React component will not have the same bug :slightly_smiling_face:)
