### ISSUE TITLE
Scatter plot: y axis with scale 'Category' shows all values as y value '0'

### ISSUE THREAD

**Issue by Archaeopteryx** [getredash/redash#3213]
### Issue Summary

A query which returns a datetime column, a column with a finite set of text values used for the y axis and with the y axis scale set to 'Category' shows all values on the x axis (y has only the label '0')

### Steps to Reproduce

1. Have a query with a datetime column and at least a second column with a limit number of text values
2. Create a new Chart > Scatter visualization with datetime as the x axis and the other column as y axis, set the scale of the y axis to 'Category'.

Expected: Data points distributed across different category values. At the moment the y axis only has '0'

### Technical details:

* Redash Version: 6.0.0-dev (was working in an earlier version, ask Mozilla data engineers which version they ran on 2018-10-26)
* Browser/OS: Firefox 65.0a1
* How did you install Redash: Mozilla did

**Comment by rafrombrc** [comment]
Just adding a comment that https://sql.telemetry.mozilla.org/queries/60688/ was the query containing the visualization that was the original source of this issue, according to IRC convo.

**Comment by emtwo** [comment]
There are a few things going on here that I will point out and we can decide what to do from there:

1. Here in this commit: https://github.com/getredash/redash/commit/9b59d1067#diff-11830b1c2a93941fe75a5bef8246c00aR320, we have a new assumption that y-axis can only be numerical values for non-bubble types of charts. Specifically in this line: https://github.com/getredash/redash/commit/9b59d1067#diff-11830b1c2a93941fe75a5bef8246c00aR320 if it's a non-numerical value, it will be set to 0. Which explains why the labels are all 0s in the shared graph.

@kravets-levko perhaps you can shed some light on whether I am understanding that correctly and why that assumption was made? It seems to me if y-axis can only be numerical, then other options such as `Category` should not be available to users. 

2. Suppose it was intentional that we can only use `bubble` for non-numerical y-axis, these still seem to be janky. Particularly here: https://github.com/getredash/redash/blob/master/client/app/visualizations/chart/plotly/utils.js#L493 the bubbles only show up if they have a size associated with them that was inputted by the user. If there is no size, no bubbles are visible. Perhaps this should default to a particular size? Or perhaps `scatter` graphs should be treated in the same manner as `bubble` graphs (they could have non-numerical y-axes).

In any case, until we get this sorted out, @Archaeopteryx, you can add an additional column in the select clause like `'5' as size`. Use the chart type `bubble` instead of `scatter`. And set the value for `Bubble size column`to this new column that is added to the select clause. You will get something that looks like the graph I attached here, which I think is what you need? 
<img width="1085" alt="screen shot 2019-01-02 at 3 05 29 pm" src="https://user-images.githubusercontent.com/784781/50610551-5e87ea80-0ea1-11e9-869b-65596b2f4f1d.png">

**Comment by kravets-levko** [comment]
Hi @Archaeopteryx and @emtwo! Thank you a lot for reporting this issue and for the help with figuring out the bug :bowing_man:
