### ISSUE TITLE
Pending invitation links broken in latest version

### ISSUE THREAD

**Issue by chang** [getredash/redash#3297]
### Issue Summary

It looks like the change in #3261 doesn't handle the case of existing users that haven't accepted their invitations yet, so users trying to sign up using invitations created in a previous version incorrectly get the "This invitation has already been accepted" message. https://github.com/getredash/redash/pull/3229/files#diff-a0c5448134fdb627ae48d25bad76393fR40

I was able to fix this in our org with:

```sql
UPDATE users
SET details = '{"is_invitation_pending": true}'::json
WHERE password_hash IS NULL
```

Maybe this case should be handled in the migration here? https://github.com/getredash/redash/blob/master/migrations/versions/e7f8a917aa8e_add_user_details_json_column.py

### Steps to Reproduce

1. Send invitation from a version prior to #3229 and #3261 
2. Upgrade to current master
3. Try to access the invitation link

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Redash Version:
* Browser/OS:
* How did you install Redash:

**Comment by arikfr** [comment]
Good catch, @chang! We can't do a migration in this case, because prior to this change there was no information on whether the user accepted the invitation or not. 

I think the solution can be to assume the invitation is pending if there is no `is_invitation_pending` key in the `details` property. To avoid code changes, I would rename the db property to `_is_invitation_pending`, and have a class property that does this check.
