### ISSUE TITLE
When creating a visualisation after running a query the query results are deleted

### ISSUE THREAD

**Issue by ifeldmanAtlassian** [getredash/redash#3372]
We are testing the latest stable version of redash (6.0.0+b10818 (7fa66654)
Found a regression when creating a new visualization, to reproduce:
0. Open a new browser tab and log into redash
1. Run a query
2. Create a new visualization
3. The X & Y drop downs are empty
4. When you cancel the visualization creation you see that the query results disappeared

Note - the issue occurs only when you run redash for the first time on a new session

**Comment by arikfr** [comment]
The issue isn't with a specific visualization, but with the query losing reference to the query result.

I think the issue happens because we don't take reference to the query result from the UI, so when first saving the query it gets saved without a query result reference (`latest_query_data_id`):

https://github.com/getredash/redash/blob/933dd753a8197708fe37432ee037a7f6bba258d5/redash/handlers/queries.py#L213-L214
