### ISSUE TITLE
New Org fails save, required field null

### ISSUE THREAD

**Issue by Rovel** [getredash/redash#3437]
### Issue Summary

Creating new organisation falis due to required field settings that do not exist, I tried with multi-org on and off and the result is the same.
Probably need some updating in the save required fields or fill settings params with the rest of the fields in the form.

### Steps to Reproduce

1. docker-compose up
2. go to http://localhost:5000/admin/organization/new/
3. fill the required fields
4. save

![screen shot 2019-02-14 at 10 20 25](https://user-images.githubusercontent.com/2469500/52786892-4e882c80-3043-11e9-9769-3210ed89f6a7.png)

### Technical details:

* Redash Version: latest 7.0-beta
* Browser/OS: chrome latest
* How did you install Redash: docker-compose

**Comment by arikfr** [comment]
The issue here is that the `Organization` model isn't setup properly with Flask Admin, and therefore it doesn't create the object properly. You can lookup Flask Admin's documentation about how to set it up correctly.

We don't provide support for the multi-org functionality in the open source context, so I'm going to close this now.

Thanks.

**Comment by Rovel** [comment]
Thanks @arikfr, so is that intentional or there is a bug here anyway? just to known...

**Comment by arikfr** [comment]
@Rovel there is no intentional bug here. It just that the Organization model using the default view, which isn't right for it.

**Comment by Rovel** [comment]
oh ok, thanks 👍
