### ISSUE TITLE
Rewrite Extensions registry not to depend on Flask app

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#3466]
- [ ] Rewrite Extensions registry not to depend on Flask app
- [ ] Bring back support for `add_periodic_tasks` (disabled in #3465)

**Comment by jezdez** [comment]
Please allow me to specify again why the backend extensions need the Flask app instance (at the moment) passed directly (and can't use flask.current_app):

- traditional Flask extensions require manual initialization of extension instances, Flask blueprints are not enough to cover the full life cycle of Flask apps
- our Docker based deployment workflow (contrary to e.g. a Python package based one) requires us to have a mechanism in place that extends Redash via separate dependencies (refs #2810) that are installed into the container
- to be able to extend the Redash backend system with own API endpoints, we're currently requiring the use of Flask-Restful's API endpoint registry)
- once we've moved to something else (#2981) the app instance is still needed to since the request handler api in anything based on Flask uses the app instance to store the handlers
- `flask.current_app` isn't set yet when extensions are loaded in `redash.create_app` since that's where the flask runtime looks for the app instance

Some ideas how to solve this:

- move the extension initialization into a signal handler for [Flask.before_first_request](http://flask.pocoo.org/docs/0.12/api/#flask.Flask.before_first_request) which is called [just before the first request is handled](https://github.com/pallets/flask/blob/a74864ec229141784374f1998324d2cbac837295/flask/app.py#L1826)
- simply rely on flask.current_app in extensions entrypoint callbacks
- move to using a Flask integration layer for initializing the Celery app, e.g. CERN's [flask-celeryext](https://github.com/inveniosoftware/flask-celeryext)

For some examples, feel free to check out https://github.com/mozilla/redash-stmo which contains a few extensions already, including examples that:

- extend a built-in query runner
- extend built-in API endpoints
- add new API endpoints
- bundle additional React components
- use a 3rd party Flask extension
- additional Celery tasks

I would be extremely happy if we were not to break any of those features 😬 But I'm also happy to work on this if you'd like and make sure the extension API becomes rock solid.

**Comment by arikfr** [comment]
> Please allow me to specify again why the backend extensions need the Flask app instance (at the moment) passed directly (and can't use `flask.current_app`):

I should've elaborated more in the issue description... The idea here is not to prevent existing use cases, but to improve the code architecture. The registry not being coupled with Flask doesn't mean we can't use it with Flask, it just means we don't need Flask to make it work in Celery.

Currently `redash.extensions.init_extensions` both iterates on `iter_entry_points` and updates the Flask app object. Once it's done the only way to get the list of extensions is to query Flask's app. We just need to introduce some other object in the middle which we can query for extensions.
