### ISSUE TITLE
Alignment issues on data sources/alert destinations pages

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#3677]
![image](https://user-images.githubusercontent.com/71468/55536721-23c16880-56c3-11e9-8208-364a2e127f83.png)

1. The cards are not aligned with the button on the left side.
2. The whitespace is uneven on the top and bottom of the card. Also there is quite large spacing between the logo and the name. 

How hard will it be to reuse the old markup we were using for these cards? It was actually quite nice :)

**Comment by arikfr** [comment]
@ranbena @gabrieldutra

**Comment by gabrieldutra** [comment]
When doing it I mainly tried to be consistent in spacing with other Settings pages (you can see that the Create button is in the exactly same position as in other pages).

> 1. The cards are not aligned with the button on the left side.

I'm afraid this one can be tricky. The difference in spacing is due to `margin` associated to the cards and the other is the `padding` from `col-X-X`. This difference even existed before:

![old-data-sources](https://user-images.githubusercontent.com/3356951/55596785-cfe56c80-5720-11e9-8b5e-550c9a92c9f7.png)

> How hard will it be to reuse the old markup we were using for these cards? It was actually quite nice :)

Quite easy -> #3679 - only need to see details

I went with Ant `List` for the sake of using an Ant Component, it ended as "acceptable" to me, as there's an issue from it I support the idea of using old markup :slightly_smiling_face:

**Comment by arikfr** [comment]
Any chance we can fix the button alignment issue too? 🙏

**Comment by ranbena** [comment]
I'll give it a try 👍
