### ISSUE TITLE
setup/*.sh scripts inconsistant use of /opt/redash

### ISSUE THREAD

**Issue by DALDEI** [getredash/redash#3727]
### Issue Summary

The docker setup scripts in setup/*.sh make inconsistent use of /opt/redash.
At the beginning of the script there is an env variable set, implying it could be another path (say a path that doesnt require sudo /root ) -- but no.  
the path /opt/redash is hard coded in many places.

Docker installs should not require local host hard coded paths in root-only-accessable directories.

**Comment by arikfr** [comment]
I believe that #3740 fixes this. I'm just not sure if this is correct:
https://github.com/getredash/redash/pull/3740/files#diff-857898594f6154f687a8e971526f0749L63

If you have the opportunity to test it out, it will help with expediting merging #3740.

Btw, what path are you planning on using instead of `/opt/redash`?

Thanks.

**Comment by jezdez** [comment]
> I believe that #3740 fixes this. I'm just not sure if this is correct:
> [getredash/redash/pull/3740/files#diff-857898594f6154f687a8e971526f0749L63](https://github.com/getredash/redash/pull/3740/files#diff-857898594f6154f687a8e971526f0749L63)

That works as expected, the resulting content is `export COMPOSE_FILE=/opt/redash/docker-compose.yml` in `~/.profile`.

> 
> If you have the opportunity to test it out, it will help with expediting merging #3740.
> 
> Btw, what path are you planning on using instead of `/opt/redash`?
> 
> Thanks.
