### ISSUE TITLE
z-Index of ant-modal-mask needs to increase

### ISSUE THREAD

**Issue by deecay** [getredash/redash#3785]
### Issue Summary

In some cases, plotly modebar appears in Choropleth and other visualization editors because of z-Index misalignment.

### Steps to Reproduce

1. Have plotly visualization shown in query editor.
2. Click New Visualization and select Map (Choropleth).
3. You can make the plotly modebar of the underlying visualization to appear over choropleth map when you hover over where the plotly modebar exsists.

Plotly `modebar` class has fixed z-Index of `1001`. Our `ant-modal-mask` and `ant-modal-wrap` both has z-Index of `1000`. Maybe we need to increase these to 1002 or more?

**Comment by kravets-levko** [comment]
Changing z-index for Ant modal will require changing it for other Ant components as well (otherwise it may break that components if using them within modals: https://github.com/ant-design/ant-design/blob/896011f5861eb4062abe7272cf657f2a644adcce/components/style/themes/default.less#L266-L273). It could be easier to fix Plotly instead (that's just another option).

**Comment by deecay** [comment]
Maybe you're right. Plotly also has other components like tooltips close to z-Index of 1000, but seems to be easier to change than Ant components.
