### ISSUE TITLE
Query results auto round numbers

### ISSUE THREAD

**Issue by flolivaud** [getredash/redash#3820]
### Issue Summary

Query results auto round numbers

### Steps to Reproduce
With Query results datasource :
`SELECT 2.4 as value;`
Will return `2`

`SELECT 2.5 as value;`
Will return `3`

**Comment by arikfr** [comment]
What type of data source did you run this query with?

Arik

**Comment by flolivaud** [comment]
@arikfr I use the url data sources. But to reproduce the bug you don't need any other datasource.

**Comment by arikfr** [comment]
@flolivaud it does not happen with every data source. It's a data source specific issue rather than a global one, therefore important to know which one is it.

Here's an example where it does not happen: https://redash-preview.netlify.com/queries/156/source

In your case: can you share the `columns` part of your URL response? (and mention which column included the number you had problem with)

**Comment by arikfr** [comment]
Resolved in #3913.
