### ISSUE TITLE
after install redash on centos7 , cannot display all svg pictures, verson6.0

### ISSUE THREAD

**Issue by yanjlee** [getredash/redash#3821]
![image](https://user-images.githubusercontent.com/4945984/58162971-bb036f00-7cb5-11e9-97b2-dedc76e98bd8.png)

after install redash on centos7 , cannot display all svg pictures, verson6.0

anyone knows ? thanks

**Comment by yanjlee** [comment]
![image](https://user-images.githubusercontent.com/4945984/58163479-ad021e00-7cb6-11e9-8d60-691cabad1950.png)

![image](https://user-images.githubusercontent.com/4945984/58163581-d753db80-7cb6-11e9-9924-076002bdbd01.png)

**Comment by yanjlee** [comment]
![image](https://user-images.githubusercontent.com/4945984/58163684-fbafb800-7cb6-11e9-803a-583a3caba4f7.png)

Please Help.

**Comment by yanjlee** [comment]
@arikfr

**Comment by justinclift** [comment]
It's probably a decent idea to check if the link given for the image is broken, or if it's just the display of the image that isn't working. :smile:

If you right click on the broken image, and choose "copy image location" (or similar wording), in theory that should copy the image address to your clipboard.

Try loading that in a new browser window or tab, and see if that works.  Also, take note of the `http://` vs `https://` part of the address, just in case there's a mismatch between the image and the address for your instance. (a mismatch is probably a bug)

Btw, is version 6 of Redash on purpose?  Asking because version 7 of Redash is available, and should work ok.

**Comment by ranbena** [comment]
Don't think there can be a mismatch since the image url is relative.
Definitely upgrade to 7 @yanjlee.

@yanjlee, what's the network error in the developer console?

**Comment by justinclift** [comment]
> what's the network error in the developer console?

Good point, didn't think of that.  Should have been super obvious. :smile:

**Comment by arikfr** [comment]
This looks like a setup issue. Unfortunately we don't have enough information to help (like how did you setup Redash? Did you use our tarball or Docker image or built on your own?).

Please provide the extra details **in a [forum](https://discuss.redash.io/c/support) post**, and we will try to help.

Thanks.

**Comment by yanjlee** [comment]
Replace the svg pictures with png version (renamed  other xx.png->alert.svg), i fixed this temporary
