### ISSUE TITLE
Need to modify git tag 'v7.0.0'

### ISSUE THREAD

**Issue by woowahan-jaehoon** [getredash/redash#3934]
### Issue Summary

`setup/docker-compose.yml` in `v7.0.0` tag has `  image: redash/redash:6.0.0.b8537` yet.
I think that need cherry-pick 1d7378f8 to release/7.0.x and retag.

### Steps to Reproduce

```bash
git clone -b 'v7.0.0' --single-branch --depth 1 git@github.com:getredash/redash.git
```

### Technical details:

* Redash Version: 7.0.0
* Browser/OS:
* How did you install Redash:

**Comment by arikfr** [comment]
As mentioned in my comment on #3935, the latest stable version of the setup script is always in the master branch. If someone wants to deploy a specific version, they should just use a different Docker tag rather than checking out a different branch or tag from the Git repo.

At some point I tried to migrate the setup scripts to their [own repository](https://github.com/getredash/setup), but never completed it (i.e. make sure getredash/setup is updated and delete setup folder in this repo). I think it might worth doing, considering the confusion it creates otherwise.

@justinclift wdyt?

**Comment by justinclift** [comment]
Having their own repo does make sense.  Let me think it over (need coffee atm). :smile:
