### ISSUE TITLE
Replace Celery with RQ

### ISSUE THREAD

**Issue by rauchy** [getredash/redash#4092]
[Celery](http://www.celeryproject.org) has been our task runner for a while, but we’ve been experiencing operational issues with it in our SaaS instance. While Celery is a respected and standard approach to perform asynchronous tasks, it has optimization benefits that simply aren’t important to us, and overall I feel that its complexity is greater than its offering, at least for our (mostly trivial) use cases.

[RQ](https://python-rq.org) has a lot in common with Celery, but it is way simpler, and could vastly reduce our project’s complexity.

In order to get a feel of RQ’s design concepts and operational shenanigans, we could start by migrating all the scheduled tasks from Celery to RQ. They can easily run side by side with the query execution tasks, which can still run in Celery for now.

**Comment by jezdez** [comment]
FWIW I'm in favor of moving away from Celery. But I wanted to also add [Spinach](https://spinach.readthedocs.io/) as an option on the table since I think it has some interesting [design choices](https://spinach.readthedocs.io/en/stable/user/design.html) compared to RQ.

It comes with:
- [support](https://spinach.readthedocs.io/en/stable/user/integrations.html) for Flask (e.g. access to Flask app inside tasks), Sentry and task batching
- BSD-licensed
- built for [Redis](https://spinach.readthedocs.io/en/stable/user/design.html#only-two-brokers)
- native retries for [tasks](https://spinach.readthedocs.io/en/stable/user/tasks.html)
- has easy optional in-memory workers for tests
- is thread-safe
- [scheduled tasks](https://spinach.readthedocs.io/en/stable/user/design.html#jobs-scheduled-for-the-future) already already built-in
- [periodic tasks](https://spinach.readthedocs.io/en/stable/user/tasks.html#periodic-tasks) don't require a separate scheduler/beat process which could fail if the container dies
- the performance behavior in my experience running [Jazzband.co](https://jazzband.co) with it is very predictable since it simply uses standard threads to execute tasks
- extensible via Blinker based [signals](https://spinach.readthedocs.io/en/stable/user/signals.html) like Flask
- [worker setup](https://spinach.readthedocs.io/en/stable/user/design.html#no-worker-entrypoint) is  left to users
- supports namespaces for running separate Spinach instances in the same interpreter (e.g. queues)
- is Python 3-only 🥇 

There are some good docs for a [production setup](https://spinach.readthedocs.io/en/stable/user/production.html) and a small [FAQ](https://spinach.readthedocs.io/en/stable/user/faq.html).

**Comment by arikfr** [comment]
Spinach is interesting, but has some concerns:

* Python 3 only: this means we need to migrate to Python 3 before ditching Celery. We have some operational issues with Celery that we would like to address asap, so not sure this is a price we can pay.
* Threads: he makes a compelling case for using threads and I can see the performance benefits considering our use case. But it still an opening for issues. We are using 30+ different database client libraries where we have no idea how thread safe they are. There is also the memory usage concern (recycling workers after N tasks helps with reducing the memory footprint). Multiprocessing and forking while not being very resources friendly proved itself over the years.
* The project is young and has virtually no community.
* @NicolasLM himself seems to recommend using RQ or Celery in production :-)

But I have to say I am intrigued. @rauchy wdyt?

**Comment by jezdez** [comment]
Definitely worth weighing the concerns @arikfr. While RQ has seen plenty of use in production systems (and has a great community of 3rd party extensions), Spinach is basically just another step down in terms of code complexity and maybe a bit more modern Python. Not saying that this is what you want, but it felt useful to mention the alternative.

> Spinach is interesting, but has some concerns:
> 
>     * Python 3 only: this means we need to migrate to Python 3 before ditching Celery. We have some operational issues with Celery that we would like to address asap, so not sure this is a price we can pay.

That's true, but effectively I think it won't be a huge difference given Python 2's EOL soon. I think I saw you write somewhere that you hope the next release will be Python2/3 compatible? 😀

>     * Threads: he makes a compelling case for using threads and I can see the performance benefits considering our use case. But it still an opening for issues. We are using 30+ different database client libraries where we have no idea how thread safe they are. There is also the memory usage concern (recycling workers after N tasks helps with reducing the memory footprint). Multiprocessing and forking while not being very resources friendly proved itself over the years.

Fair enough, I hadn't considered the 3rd party libraries, that's a big concern indeed.

> >     * The project is young and has virtually no community.

True that, given its small code size and complexity it shares RQ's low risk of of adoption, but definitely lacks the countless real world fixes in RQ over the years.

>     * @NicolasLM himself seems to recommend using RQ or Celery in production :-)

A positive thing to see coming from the maintainer in this case. They acknowledge the earliness of the product and I think simply want to say that they can't be responsible for production issues. In that sense it's the same with RQ since it's also just one main maintainer there at the moment. I think a lot of people also ignore the fact that Celery as well has had a lot of problems with securing long term maintenance when the original author stepped away.

**Comment by NicolasLM** [comment]
Hi everyone,

@jezdez thank you for the positivity regarding Spinach!

Since I have been asked by @arikfr here are my thoughts regarding replacing Celery with Spinach:

- Python 3: this is probably the most important issue raised so far. It should be possible to add Python 2.7 compatibility to Spinach but it is a fairly big task and it feels a bit backwards since 2.7 will be unsupported in just a few months.

- Thread safety: from my experience database drivers are thread-safe, at the very least connections created inside the task itself should not pose a problem.

- Threads vs processes: after glancing at the code, it seems that Redash uses Hard/Soft limits on the duration of a Celery task. This behavior cannot be replicated with threads (in Python) and is currently not supported by Spinach. That being said I'm open to implementing workers based on processes that would solve this issue (and brings other Celery features like recycling workers).

**Comment by rauchy** [comment]
You can track the progress of this issue in the [dedicated project](https://github.com/getredash/redash/projects/5).

**Comment by shinsuke-nara** [comment]
@rauchy Thank you for developing Redash. I love to use Redash.

In https://github.com/getredash/redash/issues/4092#issue-483611429, you said  `we’ve been experiencing operational issues with it in our SaaS instance.` I want to know the detail of the `operational issues`. Does the operational issues include memory leaks?

Would you tell me about that if you have time?
