### ISSUE TITLE
Query with a drop down list based on query (Allow multiple values with quotation mark) not adding quotation mark correctly

### ISSUE THREAD

**Issue by myonlylonely** [getredash/redash#4184]
### Issue Summary

Query with a drop down list based on query (Allow multiple values with quotation mark) not adding quotation mark correctly.

### Steps to Reproduce

1. Create a query with a parameter with query based dropdown list.
2. Select allow multiple values, double quotation mark.
3. Execute query, when the parameter select only 1 choice and the parameter is text, it didn't add double quotation mark and the query returns an error.

### Technical details:

* Redash Version: 8.0 Beta 2
* Browser/OS: CentOS 7
* How did you install Redash: Docker

**Comment by ranbena** [comment]
@gabrieldutra is this expected or a bug?

**Comment by gabrieldutra** [comment]
@ranbena it should have the quote mark in any case when you set them.

@myonlylonely I tried it in our [netlify preview](https://redash-preview.netlify.com/queries/123/source?p_test=%5B%22MrCirca%22%5D#219) and it seems to be adding the quotes as expected:
![Screenshot_20190925-084337](https://user-images.githubusercontent.com/3356951/65598030-e7374100-df70-11e9-8c64-1da35be2b5c5.png)

But I did notice a different issue that may be what's going on here: what happens if you remove the value the querie has, run the query, add it back and run the query again?

**Comment by myonlylonely** [comment]
I created a new query "Search Album New Sample" on netlify preview.
![image](https://user-images.githubusercontent.com/8188177/65599780-25644d00-dfd1-11e9-992f-669e8793984f.png)

But when I choose 2 items in the dropdown list, It returns the results.
![image](https://user-images.githubusercontent.com/8188177/65599825-4a58c000-dfd1-11e9-8be5-12add83df6ba.png)

When I delete 2 items to 1 item, It returns the results correctly.
![image](https://user-images.githubusercontent.com/8188177/65599860-652b3480-dfd1-11e9-9e66-7fb3f64b8aa0.png)

For the first time I created a new query with a drop down list based on query (Allow multiple values with quotation mark), it always not adding the quotation mark, and it returns an error.

**Comment by gabrieldutra** [comment]
Thanks @myonlylonely, that's exactly what I was thinking before :+1:.

It seems it's having trouble to handle empty values (for Multiple values it should allow you to leave it empty). I'll take a deeper look into it today and submit a fix PR, but a workaround for you to have this working is to save the query right after you have it working as it should.
