### ISSUE TITLE
Query Results returns to `true` when `'False' String`

### ISSUE THREAD

**Issue by ayumu838** [getredash/redash#4263]
### Issue Summary
Query Results returns to `true` when `'False' String`

### Steps to Reproduce

1. Select Datasorce to `Query Results`
2. Input `SELECT 'FALSE' AS Foo`
3. Query result is `true`

### Technical details:

* Redash Version: v7.0.0+b18042
* Browser/OS: macOS  Mojave v10.14.5 / macOS  Mojave v10.14.5
* How did you install Redash:

**Comment by kravets-levko** [comment]
Hi @ayumu838! It happens because SQLite (which is used as an engine for Query Results) does not return data types for columns, so Redash tries to infer that types. Strings `false` and `true` will infer to `TYPE_BOOLEAN`, therefore you see this result.

But detected data types don't change actual data, just the way the app will interpret them _by default_. Open Table visualization editor and change "Display As" to "Text".
