### ISSUE TITLE
Make Cypress tests work with Cypress@3.6.0

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#4286]
Running our tests with Cypress@3.5.0 doesn't work. Need to figure out what happened, until then pinning the version to 3.4.1 (#4284).

**Comment by gabrieldutra** [comment]
After checking again the changelog list I think I finally found the cause for the issue :grin:

I've read about changes in the `cy.request` command and "up to 2,000 characters of HTTP property values" and that remembered me of Chrome Logger issues with header size. I didn't bother to check deeper, but disabling it made the requests work again.

So @arikfr, how do you feel about the Chrome Logger? What passed through my mind was either use an env var to disable it in Cypress or use the `server` command instead of `dev_server` (there may be other implications on that which I'm not aware of, though). ~Also depending on its usage we can :scissors:~

I'm running the tests in the [cypress-percy-update](https://github.com/getredash/redash/tree/cypress-percy-update) branch. (There seems to be still some other problems to fix, but the `cy.request` issue went away)

**Comment by arikfr** [comment]
> use the `server` command instead of `dev_server` (there may be other implications on that which I'm not aware of, though)

This sounds like a good idea in general. Unless it has some unwanted side effects, it provides a better environment for E2E testing.

Regardless, we should consider dropping Chrome Logger. I don't remember the last time I really used it...
