### ISSUE TITLE
Query page title isn't shown on mobile in some scenarios

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#4330]
When opening a query page from the queries list, its title is hidden by the navbar.

**Comment by gabrieldutra** [comment]
While checking this issue I noticed that it couldn't be reproduced through Chrome Devtools, so I debugged it using a Remote Device:

![Screenshot from 2019-11-04 14-39-58](https://user-images.githubusercontent.com/3356951/68143941-49d91080-ff11-11e9-8559-24897defb316.png)
(Note that the whole margin is put below the Mobile Chrome navigation options)

My guess from my tests is that what specifically causes the issue is changing angular route from an scrolled page to the query page, so it keeps the scrolling information .Also it seems to need the Mobile navigation options for the issue to happen and I don't understand 100% why that is, but I'm running tests from #4337.

**Comment by gabrieldutra** [comment]
The thing with the address bar is that the `vh` unit considers it as "hidden", so when you have 100vh you'll have a hidden portion when the address bar shows up.

Adding `autoscroll` to the `ng-view` partially solves ([available here](https://deploy-preview-4337--redash-preview.netlify.com/queries/168)) the issue and makes the behavior similar to what it was previous to the fixed navbar: the "hidden portion" comes back to be the bottom controls on the Query Page (# of rows returned, execute button).

@arikfr wdyt of using that until the React Migration for the query page as a few mobile updates can be done along with it?

**Comment by arikfr** [comment]
> @arikfr wdyt of using that until the React Migration for the query page as a few mobile updates can be done along with it?

:+1:
