### ISSUE TITLE
“New Query” doesn’t work when you’re already on a query page

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#4549]
1. Open some query.
2. Click on “New Query”.

The URL will update to `/queries/new` but the page stays the same with the previous query loaded.

**Comment by gabrieldutra** [comment]
:thinking:, I could not reproduce it directly (tried in SaaS too), perhaps it happens in an specific context?

![new-query](https://user-images.githubusercontent.com/3356951/72446897-2513db80-3793-11ea-9dfd-29f8ed581a6b.gif)

**Comment by arikfr** [comment]
@gabrieldutra it doesn’t happen on SaaS, because SaaS doesn’t use the latest React version fo these pages.

It happened to me with the preview instance — but not sure if the main one (as you have in the screenshot above). Maybe it was your branch with the results view? I will check again and report.

**Comment by gabrieldutra** [comment]
@arikfr I think I just found what triggers this issue when you create more than one query:
1. Create a new query and save it (it will redirect you and just update the url);
2. Click on "New Query" to create another one;

I think it's caused because of the `navigateTo` without reloading the angular controller. In any case, it seems #4525 fixes it with the new router.

**Comment by kravets-levko** [comment]
Was fixed #4525, so I think it could be closed now
