### ISSUE TITLE
Query execution status “flickers”

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#4550]
The new query execution status (query in queue -> executing -> loading results) seems like it’s flickers (removed from view and then rendered again) on status changes. Also it seems like its height is being changed.

Need to make sure that as long as the query is executing, we render the same element and only change its text.

**Comment by gabrieldutra** [comment]
I couldn't see it being removed and rendered again (except when results are done), but I did saw the height changing because the last state (Loading results) doesn't have a button, and the button was making a slightly increased height in the other states. It seems an easy fix is adding padding to the text or using min-height in the whole Alert.

Current flow:
![status-changes](https://user-images.githubusercontent.com/3356951/72474628-f95f1880-37c7-11ea-9d14-d4608bb20962.gif)

**Comment by arikfr** [comment]
Got it. Let's add the padding then. 👍

Arik
