### ISSUE TITLE
Multi-Filters: "select all" makes table view unscrollable

### ISSUE THREAD

**Issue by susodapop** [getredash/redash#4772]
### Issue Summary

At 720p screen resolution, the multi-select filter widget makes the table unscrollable if too many values are selected.

![image](https://user-images.githubusercontent.com/17067911/78290291-25498a80-74e9-11ea-8dd4-1832446023c0.png)

I don't think it depends on the screen resolution. But whether the `<select>` widget expands to the bottom of the view port. If it does, scrolling breaks.

### Steps to Reproduce

I added [an example](https://redash-preview.netlify.com/queries/358/source) on redash-preview.

1. Click "select all" in the multi-filter
2. Use responsive mode in your browser to simulate 1280x720 resolution
3. Try scrolling down to see the table

#### Secondary Bug 

The **Select All** prompt  is stuck in `checked` state, even after clicking **clear**.

<img width="467" alt="image" src="https://user-images.githubusercontent.com/17067911/78290035-b53b0480-74e8-11ea-9f60-aac1253ff0fe.png">

### Technical details:

* Redash Version: v9 Alpha
* Browser/OS: FF
* How did you install Redash: Redash-Preview

**Comment by gabrieldutra** [comment]
Simple solution I see: add a `min-height` to the table. Caveat: it will create two scroll areas.

More robust one: Since we use JS to define whether the page has fixed layout, try to check if there's enough room for the table in a fixed layout before defining it with a fixed layout. It's mostly an idea, it can be that we can't go any further than checking the page height as well.

**Comment by arikfr** [comment]
Can we change the filter to show "option, option 2 + X others" like we do for parameters now to reduce the chances of this happening?
