### ISSUE TITLE
yyyy-mm-dd formatted strings visualized as epoch milliseconds

### ISSUE THREAD

**Issue by Fraznist** [getredash/redash#5237]
The following query reproduces the issue using a snowflake data source, but a query with same logic should reproduce the error in other databases as well. I have reproduced it with an sql_server data source as well.

`select current_date(), to_varchar(current_date(), 'yyyy-mm-dd') as aaa
union
select current_date(), null as aaa;`

The minimal requirement to reproduce is a 'yyyy-mm-dd' date formatted string, and a null valued element in the same column. Therefore the following reproduces as well:

`select to_varchar(current_date(), 'yyyy-mm-dd') as aaa
union
select null as aaa;`

This time, the null row isn't visualized at all, which is probably a different error altogether. The wrong formatting is still happening though.

Technical Details:
- Redash cloud version
- MacOS Catalina + Firefox / Chrome

**Comment by kravets-levko** [comment]
Hi @Fraznist! Can you please add some screenshots - where exactly you get the wrong data representation?

**Comment by Fraznist** [comment]
Of course: ![image](https://user-images.githubusercontent.com/35821640/97157188-d5822780-1788-11eb-8aa8-a4923bc91303.png)
The wrong representation converts the yyyy-mm-dd into epoch milliseconds timestamp, in our case 1603670400000 is Monday, October 26, 2020 12:00:00 AM GMT.
Also downloading the results as csv or tsv uses the intended representation, so I strongly suspect the js frontend. Also this just smells like something js would do 😝

**Comment by kravets-levko** [comment]
@Fraznist I think I know what's wrong there. We have a legacy code (JS) that tries to detect some column types. `\d{4}-\d{2}-\d{2}` pattern is recognised as date and converted to Moment instance. But at the same time, probably Table visualization "decides" that this column should be string. And you're getting just a timestamp - default string representation of Moment instance. Could you please try to open visualization settings and check a "Display as" input there? What happens if you set it to "Date/Time"?

**Comment by Fraznist** [comment]
I see, makes sense. Changing display into Date/Time worked. It just seemed odd that the frontend started assuming data types while the columns are explicitly typed by the data source. Glad its figured out

**Comment by kravets-levko** [comment]
I'm glad that it works for you. Of course it's a bit weird behavior, but currently we cannot just remove that legacy code because it will break backward compatibility. In most cases it works fine, and user can always change settings manually, so I think it's not critical.

I'm closing this issue for now, but if you think it's critical and/or have any ideas how to fix it - feel free to reopen and let's continue discussion.
