### ISSUE TITLE
Table column names should not be auto-capitalized

### ISSUE THREAD

**Issue by stanhu** [getredash/redash#565]
It appears that all table column names are automatically capitalized. This should be left to the user to decide in the `SELECT ... AS ...` query.

**Comment by arikfr** [comment]
So far it's been convenient, because it's easier to handle lower cased names in the query itself, while it's nicer to read capitalized names in the user interface. Also some databases (like Postgres) are case insensitive unless you quote the column name, which adds more complexity to writing the query.

When we get to implementing options for the table visualization, we can make this one of the option. Until then, unless there is a really good reason to avoid it, I prefer we continue auto-capitalizing.
