### ISSUE TITLE
Can't add new users without email configured in v10

### ISSUE THREAD

**Issue by adm7373** [getredash/redash#5700]
### Issue Summary

In previous versions, an Admin could add a user and get an "invite link" to send to that user, which would allow them to log in. 

Admins could also generate a "reset password link" to send to users, which would allow the user to set a new password.

These features seem to have disappeared in version 10 and both user flows instead only generate an email to be sent to the user. If email is not configured, this means that new users effectively can't be added and passwords can never be reset (until email is configured). 

### Steps to Reproduce

1. Run Redash v10 without email configured
2. Add a new User

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

This seems to be a regression from previous versions' functionality

### Technical details:

* Redash Version: 10.1.0
* Browser/OS: Chrome
* How did you install Redash: docker-compose in the official AMI in us-east-1

**Comment by susodapop** [comment]
Sorry to only now answer this. The behaviour you identified [is still present in V10](https://github.com/getredash/redash/blob/2589bef1f21b7c84e4ceacdf5cd2c620bdedb111/client/app/pages/users/UsersList.jsx#L155). It did not change at all since V8. 

To fix this, you need to unset the `REDASH_MAIL_DEFAULT_SENDER` environment variable in your `.env` file.

What's happening is that Redash uses this environment variable to determine if an email server has been configured. If you unset it, Redash knows the server is not configured and will display the link.




### Example

Here's a screenshot of the modal in V10.1

<img width="1618" alt="CleanShot 2022-07-02 at 22 29 36@2x" src="https://user-images.githubusercontent.com/17067911/177023367-4c6c9749-99fd-4c61-b275-14929e26469c.png">
