### ISSUE TITLE
Display Epoch Time

### ISSUE THREAD

**Issue by dwori** [getredash/redash#5707]
### Issue Summary

I have some time series data for temperature that should be visualized with Redash. The timestamps have Epoch time / Unix Time format. If I create a chart and put the timestamp on the x-axis, it does not show the right date. I checked the timestamps with a converter and there everything got displayed correct. It always shows a date from 1970 and not even the right day.

<img width="1379" alt="image" src="https://user-images.githubusercontent.com/73217570/154665208-495769ed-e738-4db7-b753-1bb910333a81.png">

<img width="1379" alt="image" src="https://user-images.githubusercontent.com/73217570/154665275-17e41473-bda7-4a38-bb3c-23f1c5cec836.png">

### Steps to Reproduce

1. Connect a MongoDB with Unix Time - timestamps.
2. Create a Query
3. Create a chart with value on y-axis and timestamp on x-axis
4. X-axis scale either auto detect or datetime

As described in Summary

### Technical details:

* Redash Version: 
<img width="188" alt="image" src="https://user-images.githubusercontent.com/73217570/154665512-92f7993d-18ed-441f-b15c-160e986f799e.png">

* Browser/OS: Safari/MacOS & Chrome/Windows
* How did you install Redash: In Kubernetes

**Comment by susodapop** [comment]
Are you able to reproduce this on V10? It would be helpful to see it on our [preview instance](https://redash-preview.netlify.app/) since we don't have a  mongo instance to connect with.

**Comment by susodapop** [comment]
I played around with this a little and I think the issue is your timestamps aren't a complete. They don't include the milliseconds precision that `moment.js` needs. 

Observe the following:

```sql
-- This query pulls a complete unix time stamp
select '1647547518111', 10
union all
select '1647647518200', 20
```

And makes the following chart on our preview instance:

<img width="1386" alt="CleanShot 2022-03-17 at 15 10 13@2x" src="https://user-images.githubusercontent.com/17067911/158887136-a681ac91-be9e-4ec2-954b-d28bb355a8f2.png">

But if we remove the final three digits of precision from the timestamps, the visualisation goes wonky:


```sql
-- This query pulls a truncated unix time stamp without milliseconds precision
select '1647547518', 10
union all
select '1647647518', 20
```

<img width="1382" alt="CleanShot 2022-03-17 at 15 11 12@2x" src="https://user-images.githubusercontent.com/17067911/158887329-57511eb9-cd60-4657-95e6-39111e2ff693.png">

## Workaround

Since the timestamps are stored in mongo without milliseconds precision, you can transform them by multiplying by 1000 before visualising the data.
