### ISSUE TITLE
Yarn install fails due to eslint error in Redash sql-formatter fork

### ISSUE THREAD

**Issue by deed02392** [getredash/redash#5770]
https://github.com/getredash/redash/blob/cabe33394bf4ea4155c6d45e779298e43a0d9e4a/yarn.lock#L14628

If you try to follow the official https://redash.io/help/open-source/dev-guide/docker guide, you'll encounter a fatal error trying to install Node packages with Yarn:

yarn --frozen-lockfile

eslint fails in the `npm check` phase for sql-formatter.

**Comment by susodapop** [comment]
What version of Node / yarn are you running? I don't encounter this error using Node 14 and Yarn 1.22

**Comment by deed02392** [comment]
I can't even build the Docker container on main without skipping front-end.

**Comment by susodapop** [comment]
I understand that. You should share your node and yarn version, and your OS so we can help To solve it. Since hundreds of others successfully built the project recently this likely isn't a bug. Rather it's a problem
with your specific environment.

Also, conventionally we **don't** build the frontenis dependencies within the Docker container. Our official instructions advise you to do this on your local box.
