### ISSUE TITLE
Refresh on wrong day when non-UTC timezone crossing day boundary

### ISSUE THREAD

**Issue by rutson** [getredash/redash#5775]
### Issue Summary

I expect this to happen at 00:15 on a Monday:
<img width="504" alt="image" src="https://user-images.githubusercontent.com/14196062/175931017-2a18d57f-a494-437a-a1f4-e11d4567a2ec.png">

Redash refreshes at 00:15 on a Tuesday:
<img width="255" alt="image" src="https://user-images.githubusercontent.com/14196062/175931298-c7d58eba-1656-4c93-8780-aa1fb206f3a3.png">

### Technical details:

Version: 10.1.0 (2589bef1)

**Comment by susodapop** [comment]
As confusing as this is, I believe it's expected behaviour. When you save a refresh schedule, Redash converts it from your system time (BST) to UTC. This conversion appears in parentheses to the right of your **On Time** selection.

Since BST is one hour ahead of UTC, ideally your query would run at 0015 BST **Monday** which is 2315 UTC **Sunday**.

Here's the pitfall: the conversion uses modular arithmetic. Therefore subtracting one hour from 0015 does not equal 2315 the previous day, but 2315 on the _same_ day. So to make your query run at 0015 BST Monday, your schedule should be:

**Refresh Every**: 1 Week
**On Time**: 0015
**On Day**: _Sunday_

This will cause the query to execute to execute at 2315 Sunday, which is 0015 BST Monday.
