### ISSUE TITLE
Query parameters: add default values support and UI

### ISSUE THREAD

**Issue by toyama0919** [getredash/redash#583]
Background on current support for query parameters: http://demo.redash.io/queries/146/source?p_action=create

Things to implement:

- [ ] UI for entering the parameter value.
- [ ] Support for setting the default value and type of parameter.

**Comment by arikfr** [comment]
This way isn't working, because of the way re:dash decides if there needs to be a parameter in the query. But I'm already working on an interface for query parameters that also supports setting a default value.

I have good progress on it, but currently busy with some other project. Maybe late next week I will make the pull request.

**Comment by toyama-h** [comment]
OK Thanks!
I expect it :blush:

**Comment by AntoineAugusti** [comment]
@arikfr Hey! Where can I follow progress on this? Any related PRs / issues? Is there an ETA for this awesome feature?

**Comment by arikfr** [comment]
@AntoineAugusti subscribe to this issue & the [newsletter](redash.io/newsletter.html) to be updated.

I try not to promise ETA, although I hope to get to this one soon.

**Comment by arikfr** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;rMYZf4dj&#x2F;10-ui-for-query-parameters"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> UI for query parameters</a>
