### ISSUE TITLE
Feature Request: cancel scheduling of failing query after X retries

### ISSUE THREAD

**Issue by stanhu** [getredash/redash#613]
I have a Redshift query that seems to result in an overflow error:

```
[2015-10-16 17:37:27,957: ERROR/MainProcess] Task redash.tasks.execute_query[f36ec80c-e9f2-4dec-bfb0-3d44a0920f5c] raised unexpected: Exception('Integer data overflow (multiplication)\nDETAIL:  \n  -----------------------------------------------\n  error:  Integer data overflow (multiplication)\n  code:      1058\n  context:   \n  query:     2268469\n  location:  numeric.hpp:325\n  process:   query1_64 [pid=26484]\n  -----------------------------------------------\n\n',)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/redash/redash.0.8.0.stanhu/redash/tasks.py", line 24, in __call__
    return super(BaseTask, self).__call__(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 437, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/redash/redash.0.8.0.stanhu/redash/tasks.py", line 312, in execute_query
    raise Exception(error)
Exception: Integer data overflow (multiplication)
DETAIL:  
  -----------------------------------------------
  error:  Integer data overflow (multiplication)
  code:      1058
  context:   
  query:     2268469
  location:  numeric.hpp:325
  process:   query1_64 [pid=26484]
  -----------------------------------------------
```

It appears that this exception causes celery to retry the same query again and again, causing our database load to be sustained at a high load.

There ought to be a way in redash to alert for these kinds of exceptions and log failed attempts. This one was buried in a supervisor log, and I had to look in the Redshift query log to see that it was trying over and over.

Also, this seems to suggest there are cases where retries are not desirable. I can see the usefulness of retrying due to a DB connection issue, but exceptions caused by a bad query should not warrant a retry.

**Comment by arikfr** [comment]
Since we added alerts, re:dash can send emails, and I was indeed thinking of sending a report when query fails to execute more than X times.

Also not retrying queries that failed due to bad syntax (vs. different kind of errors), is a good idea. Although in this case, I suspect the error is reported more like a connection error rather than syntax one. Maybe we should have failures count instead and stop retrying after a few times.

**Comment by arikfr** [comment]
Just to confirm, this was a scheduled query - correct?
Because non scheduled ones, not supposed to be retried.

**Comment by stanhu** [comment]
Yes, this was a scheduled query.

Thanks, I think it would be a good idea to stop after X tries.

**Comment by gabrielcrowdtilt** [comment]
+1 Really need this feature, as well.

**Comment by rakeshsingh** [comment]
+1 for this feature. Will end up saving resources and also tell us the areas to debug/look into

**Comment by tdawber** [comment]
+1

When you have a query set up to run 'Every 12 hours', Redash will attempt to run the query after 12 hours, and, if it fails, it will continue to attempt to run the query every single minute.  I assume, after seeing that the query still hasn't been refreshed since more than 12 hours ago.

This 'every minute' behaviour makes this feel a bit more like a bug than a feature.

**Comment by ChrisLocus** [comment]
And when the query is issuing say a "COPY" command from S3 it can take your Redshift disk usage temporarily to 100%.

This is a feature request about retry options. 
However, there is bug that is critical behind this. 
What is the status of it?

**Comment by rohanpd** [comment]
+1 With over 2000 queries. This issue hits us daily now.

The usual scenario is that someone has changed the DDL for a table and all of a sudden any scheduled queries hitting that table start fail and repeat every few seconds. 

@arikfr if you have any simple ideas of how we can implement this change please let us know. If it's simple enough we will attempt to contribute it.

**Comment by ChrisLocus** [comment]
@rohanpd see #1281

**Comment by arikfr** [comment]
@rohanpd I have ~5K tasks I run every hour just with failed queries... I feel the pain too, but there were always bigger things.

The idea is simple:
1. Store in Redis data about the last failure(s) of a query.
2. After it passes a threshold of X failures (configuration), cancel its scheduling and email the query owner.
3. Bonus: to handle temporary issues (like connectivity), implement exponential backoff for the retry. Otherwise the scheduler will retry all X attempts very quickly (or the user will need to give it a large X).
4. We should maintain a list of such failed queries (so we can show it in the admin UI), but maintain consistent size for it (like we do with the QueryTaskTracker lists).

**Comment by ChrisLocus** [comment]
Excellent idea(s) @arikfr. 

If I ever get any free cycles I need to get more involved - this would be great to take on but I know I'm slammed for a while.

**Comment by AntoineAugusti** [comment]
Can't wait for this. This kills our cluster once every few weeks and it's always hard to find what actually happened and caused the issue (until I pinpoint Redash)

**Comment by arikfr** [comment]
Very relevant: #1584.

**Comment by arikfr** [comment]
With #1584 and #1774 I think it's safe to close this one.

**Comment by Ralnoc** [comment]
This is good to see getting added to the current versions. Is there details on how to clean up a scheduled query that is in this state? (i.e. if we have a query in this endless retry state, how do we stop it?)
