### ISSUE TITLE
Visualization "Counter" became extremely small after updating the latest Docker preview image

### ISSUE THREAD

**Issue by myonlylonely** [getredash/redash#6521]
### Issue Summary

Visualization "Counter" became extremely small after updating the latest Docker image. It is related to the recent commit https://github.com/getredash/redash/commit/2795e1b7a08320849e86c36f94dad70ce69038a5. The `getCounterScale` calculation is not correct. Could we revert this commit? And how could this commit pass the visual CI test, maybe we should also change the CI test.

### Steps to Reproduce

1. Create a counter visualization.

Before the commit :

<img width="470" alt="image" src="https://github.com/getredash/redash/assets/8188177/6c6b6217-7f31-4761-af47-8d4522707cec">

After the commit:
<img width="483" alt="image" src="https://github.com/getredash/redash/assets/8188177/be8bbed1-9597-4826-8115-82f02ac259ae">

### Technical details:

* Redash Version: 23.10.0-dev
* Browser/OS: Chrome 118.0.5993.70
* How did you install Redash: Docker

**Comment by justinclift** [comment]
@eradman This'll probably be of interest to you. :smile:

**Comment by eradman** [comment]
The difficulty here is that if the window is resized > 800 pixes (aproximately) the preview area for each visualization switches from full height to a condensed view. Since the counter widget resizes based on the height of the parent container the text was small.

This is corrected in commit 1a3d0de72293c7b6d2ff090f0e3d08c095214fad

![counter](https://github.com/getredash/redash/assets/1175398/033cd041-585a-455c-91b1-f2820779d72b)

**Comment by myonlylonely** [comment]
Is this commit merged into the master branch?

**Comment by eradman** [comment]
Yes this is master, although we made a mistake in the way we merged it. See 6b981972f0090522deb2a575504316274ef90a17

@justinclift what is the best way to tell if the Docker preview image was updated?

**Comment by justinclift** [comment]
The `preview` tag in the list here should give a rough idea of when it was last updated:

https://hub.docker.com/r/redash/redash/tags

That's reasonable for ballpark estimates.

For a more accurate indication, the better approach is to look at the commit list on the Redash `master` branch:

https://github.com/getredash/redash/commits/master

Then work out the commit you're interested in, and check if the CI task called `build-docker-image` successfully ran for it.  If it or a later one did, then that `preview` image on Docker Hub should contain the code you're after.

---

That being said, we're having some issues with the building of that `preview` image since merging the `arm64` PR the other day.

The image building was initially completing failing since then, though now we're trying a different approach (increased timeout value).  Now the image build is taking much longer.  5+ hours so far on the first build (still underway presently) on the first image getting built after increasing the timeout. :sweat_smile:

**Comment by myonlylonely** [comment]
@justinclift It is still quite small compared to before in the dashboard.
![image](https://github.com/getredash/redash/assets/8188177/e524b1ba-9c37-4a63-8bb4-19f17d8179f9)

**Comment by justinclift** [comment]
@eradman ^^^

**Comment by eradman** [comment]
The logic I used for the preview is that it should scale up to the maximum size to be displayed in a dashboard widget. This means the text will not be huge, but will be an accurate preview.

@myonlylonely if you think this is too small, please provide a complete screenshot of the final dashboard.

**Comment by eradman** [comment]
I think what this suggests is that the the font size specified in pixels doesn't work on a high-DPI display.
I'm not running a high-resolution monitor so I didn't notice. I'll investigate.

**Comment by myonlylonely** [comment]
Yes, I'm using a HiDPI monitor on a MacBook. Chrome Dev Tools could change DPI scale, maybe you could try that.

**Comment by justinclift** [comment]
@myonlylonely Would you be ok to try the very newest Redash `preview` image from Docker Hub?

Eric created a new PR (#6537) which seems like it should solve this.  In theory. :smile:

**Comment by myonlylonely** [comment]
@justinclift 
On dashboard, It is bigger than the previous commit, but still relatively small than the original ones.
This is the screenshot before the commit 2795e1b7a08320849e86c36f94dad70ce69038a5:
![image](https://github.com/getredash/redash/assets/8188177/b7d6f447-45f5-4133-9552-6da8561ffeae)

The latest preview docker image
![image](https://github.com/getredash/redash/assets/8188177/6aa72e4a-c40a-43f9-97b7-1f855e5f507e)

And embed query is still small in the latest preview image.
![image](https://github.com/getredash/redash/assets/8188177/ab2efa0b-e472-4f07-8196-667caf7f84c9)

**Comment by justinclift** [comment]
@myonlylonely Thanks for testing it. :smile:

Sounds like further work is still required on this piece. :wink:

**Comment by eradman** [comment]
I'm investigating..

@myonlylonely can you confirm that the preview docker image picked up the latest change?

```
$ docker run -t $IMAGE grep -A4 'function getCounterStyles' viz-lib/src/visualizations/counter/Renderer.tsx
function getCounterStyles(scale: any) {
  return {
    fontSize: `${scale}pt`,
  };
}
```

**Comment by myonlylonely** [comment]
@eradman I just pulled the repo, and build a local docker image myself. I could confirm the latest commit is not working.

**Comment by eradman** [comment]
Here is how to simulate a HiDPI display:

```
/usr/local/bin/chrome  --force-device-scale-factor=1.8 %U
```

**Comment by justinclift** [comment]
Oh, that's a super useful tip. :smile:

**Comment by eradman** [comment]
I started a discussion on the method we use to render counter widget text: https://github.com/getredash/redash/discussions/6542

Once we have established the desired end result, we should be able to close in on a solution!

The origonal problem in this ticket was solved. Perhaps we should start a new ticket to discuss HiDPI rendering?

**Comment by myonlylonely** [comment]
> I started a discussion on the method we use to render counter widget text: #6542
> 
> Once we have established the desired end result, we should be able to close in on a solution!
> 
> The origonal problem in this ticket was solved. Perhaps we should start a new ticket to discuss HiDPI rendering?

No, I just tried on a non-HiDPI screen, after 593b6ae6edf69e472975cecc85ffbd0e3a8e659a, it is still a lot smaller in the dashboard and embed queries than the original Redash design. 
The current size is the same on a non-HiDPI or HiDPI screen (but smaller than the original design).
I really think we should revert this commit, until we have a perfect solution.

**Comment by eradman** [comment]
The changes to the counter widgets were reverted. Closing
