### ISSUE TITLE
Different Result

### ISSUE THREAD

**Issue by zkenstein** [getredash/redash#6576]
Anyone faced different result if run on redash and DBeaver? I run a simple count in redash but the results is different if I run over DBeaver. Redash return a wrong one

**Comment by guidopetri** [comment]
@zkenstein I don't think that's possible unless you are connecting to two different (but similar) databases, or unless you're using cached query results. Could you double check and perhaps post a reproducible example?

**Comment by Auburngrads** [comment]
@guidopetri - I'm seeing a similar issue (getting a different result when I use the ReDash webapp and the ReDash API on my local machine)

I have a DataBricks routine that queries data and overwrites an output table each week (call this `table A`).  I also append this output table to a historical archive (call this `table B`).

I create `table A` to make it simple for users to query and export the data using Redash.  I also use the Redash API on my local machine.  

The issue I'm seeing is that if I use the Redash webapp I get the current version of `table A` (which contains data collected between '2023-12-25' and '2023-12-29'). When I use the API to run the same query, I get data from the previous week ('2023-12-18' to '2023-12-22').

What I don't understand is how this occurs since `table A` no longer contains data from the '2023-12-18' to '2023-12-22' timespan as it's been overwritten with data from the '2023-12-25' to '2023-12-29' timespan.

Perhaps I'm doing something wrong in how I'm using the API.  If so, I appreciate help in understanding my error.

**Comment by guidopetri** [comment]
Can't duplicate without an example ¯\\\_(ツ)\_/¯
