### ISSUE TITLE
User can't save query without query text

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#669]
(seems like it doesn't pass the `data_source_id`)

**Comment by alonho** [comment]
Can't reproduce.. I created a query, saved, it worked. Also tried creating, renaming and saving.

**Comment by arikfr** [comment]
STR:
1. Open new query.
2. Change query name.
3. Hit enter. Soon after "Can't save query" message appears.

**Comment by alonho** [comment]
I tried pressing the save button and it worked through there. 

This happens because update to the name/description is considered a partial update and sets only the name/description field. When that happens and a query was just created, there's no id, so the api call that is used is 'create query' and not 'update query'. 'create query' expects a data source id.

**Comment by arikfr** [comment]
OK, it makes sense now. How about we don't try doing partial save until
query has an id?
