### ISSUE TITLE
Migrate content and Users

### ISSUE THREAD

**Issue by puneethpotu** [getredash/redash#697]
Hi

Is there a safeway to backup the content from one redash server and migrate it over to another redash server.
I am looking to migrate Queries, datasources, Dashboards and Users.

Thank you!

**Comment by arikfr** [comment]
Currently the only way is to backup the postgres database re:dash uses. It's quite easy to do with `pg_dump`.

If your'e migrating data between re:dash instances, make sure to run the same version on both.

**Comment by tharunpalla** [comment]
HI,

I am trying to do the same, back up the content from one server to other. Currently I have the same redash versions on both the instances and used pg_dump to copy the postgres data. However, I don't see the queries, data sources and dashboards on the new redash UI for some reason.

Backup commands:
`docker exec -t redash_postgres_1 pg_dump -U postgres > backup_redash_postgres.sql
  cat backup_redash_postgres.sql | docker exec -i redash-postgres-1 psql -U postgres
`

Can you provide any suggestions or recommendations to fix this?

**Comment by justinclift** [comment]
Yep.  As well as backing up the database, you also need to copy the `env` file from your source Redash install to the new one.

The `env` file contains the encryption keys used for sensitive info stored in the database, so that's why you're not seeing that data in your new Redash.

The file is *probably* located at `/opt/redash/env` on the source server.  You can probably just copy it across to the new server, then restart Redash... and you should be good to go.

In theory. :wink:

**Comment by tharunpalla** [comment]
What about the REDASH_DATABASE_URL and POSTGRES_PASSWORD? Do we need to copy them all from old instance to new one?

**Comment by justinclift** [comment]
In theory, those values should be in the `env` file.  If the database url has changed (eg by moving the server) then you **might** need to update it in the env file (it's just text) before it all works.
