### ISSUE TITLE
Script runner is not working anymore. Alternative version proposal

### ISSUE THREAD

**Issue by luke14free** [getredash/redash#819]
I used to run scripts using the query runner which worked fine in 0.8.3 but after the update is not really working anymore. I created a "more insecure version" of it (since security doesn't play a big role for me on this specific server) which works with the latest stable version (0.9.1b) you can find it here: https://gist.github.com/luke14free/4d2545b5a071dc1afca6

**Comment by arikfr** [comment]
Maybe the issue you have is because we removed the script query runner from the enabled by default query runners list? If it is, you can enable it by adding to your .env (or whatever way you have of passing env variables to your Re:dash):

```
REDASH_ADDITIONAL_QUERY_RUNNERS=redash.query_runner.script
```

If you don't mind about security, consider enabling the Python query runner.

And if you like, you're welcome to submit a pull request with your insecure query runner.

(I'm closing this, by you're welcome to continue the discussion)

**Comment by luke14free** [comment]
Yes, I am just leaving this as a reference. I have tried to enable the standard script runner but the issue is that after upgrading the system was complaining about it not having a ```syntax``` attribute and a defined type classmethod (which I added both in my script). The python executor is simply unpractical for our usages, importing libraries was a pain (imports like from xxx.yyy import zzz don't work) and we could not call r scripts or anything else. Also I was wondering why the script executor was not documented at all. 

As soon as I have time I will work on a pr (I am also experimenting with error bars in the graphs).

Best.
