### ISSUE TITLE
'Series Options' not saved with visualization

### ISSUE THREAD

**Issue by mfinkle** [getredash/redash#871]
I have a bar chart with 4 Y series. Three are stacked on the left axis. One is a line, on the right axis.

After making changes in the Series Options section, like changing one series to a line on the right axis, adding labels and specific colors, the visualization looks correct. I save using the "Save" button at the bottom of the editor.

Closing the query and re-opening shows that my Series Options changes have been lost.

Using re:dash "0.9.1+b1377"

**Comment by arikfr** [comment]
I think you're experiencing #802, which was fixed in #826 and part of the 0.9.2 release. The good news are that the options are actually getting saved, and once you upgrade you should see your visualizations as defined.

I'm going to "package" 0.9.2 in the next few days, but you can already upgrade to it.

**Comment by arikfr** [comment]
0.9.2 has been released. Please reopen if issue persists after upgrading.
