### ISSUE TITLE
Use Marshmallow for json marshalling/serialization

### ISSUE THREAD

**Issue by jeffwidman** [getredash/redash#874]
Partially creating this as an FYI re: plans in `flask-restful` (which `redash` depends on): https://github.com/flask-restful/flask-restful/issues/335

I'm still new to this codebase, but I suspect there's some custom API code somewhere that would benefit from ripping out and replacing with `flask-marshmallow`... It just adds a lot of flexibility for constructing endpoints by nesting and re-using different schema sections.

**Comment by arikfr** [comment]
I want to take out the serialization code from the models into a place of their own, so utilizing `marshmallow` for that might be a good idea. 

While reviewing the discussion on that issue, I stumbled at [flask-apispec](https://github.com/jmcarp/flask-apispec). Maybe we can switch to using it instead of `flask-restful`, to get the Swagger documentation of the API?

As an alternative, I've recently started playing with api-blueprint, and started documenting the Re:dash's API: docs.redash.apiary.io. But still haven't decided if having the API documented outside the code is a good idea or not. It has the benefit of making sure the API doesn't break, but the downside is that it might become stale if we're not proactive about it.

**Comment by jeffwidman** [comment]
> But still haven't decided if having the API documented outside the code is a good idea or not. It has the benefit of making sure the API doesn't break, but the downside is that it might become stale if we're not proactive about it.

I think it's wiser, at least right now, to keep the API docs as closely integrated with the code as possible. The current docs for redash are already confusing and not well maintained, so assuming this will change with the API docs probably isn't realistic. I haven't played with it, `flask-apispec` is probably fine--although it does add another dependency in Swagger.

**Comment by arikfr** [comment]
I agree that we need to optimize for having more updated documentation than anything else. But some work is required either we will use `flask-apispec` or external documentation. 

So the decision points will be:
1. What requires less work?
2. What will be easier to maintain looking forward?

If `flask-apispec` auto generates most of the documentation based on the `marshmallow` definitions, then it definitely wins on both fronts.

**Comment by arikfr** [comment]
Closing in favor of #2981.
